-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity busqueda_cam is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    tree_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    tree_V_ce0 : OUT STD_LOGIC;
    tree_V_q0 : IN STD_LOGIC_VECTOR (23 downto 0);
    tree_V_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    tree_V_ce1 : OUT STD_LOGIC;
    tree_V_q1 : IN STD_LOGIC_VECTOR (23 downto 0);
    nodo_V : IN STD_LOGIC_VECTOR (10 downto 0);
    relationship_V : IN STD_LOGIC_VECTOR (1 downto 0);
    fatherSearch : IN STD_LOGIC;
    result_V_V_din : OUT STD_LOGIC_VECTOR (10 downto 0);
    result_V_V_full_n : IN STD_LOGIC;
    result_V_V_write : OUT STD_LOGIC );
end;


architecture behav of busqueda_cam is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_pp1_stage0 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_pp1_stage1 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv11_2 : STD_LOGIC_VECTOR (10 downto 0) := "00000000010";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal result_V_V_blk_n : STD_LOGIC;
    signal and_ln25_fu_241_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp1_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp1_stage0 : signal is "none";
    signal ap_enable_reg_pp1_iter1 : STD_LOGIC := '0';
    signal ap_block_pp1_stage0 : BOOLEAN;
    signal or_ln36_reg_436 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp1_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp1_stage1 : signal is "none";
    signal ap_block_pp1_stage1 : BOOLEAN;
    signal or_ln37_reg_445 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal or_ln46_reg_399 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal or_ln47_reg_408 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal and_ln25_reg_373 : STD_LOGIC_VECTOR (0 downto 0);
    signal i1_0_reg_151 : STD_LOGIC_VECTOR (10 downto 0);
    signal i_0_reg_163 : STD_LOGIC_VECTOR (10 downto 0);
    signal fatherSearch_read_read_fu_84_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal icmp_ln36_1_fu_247_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln36_1_reg_377 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_253_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_reg_385 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal or_ln46_fu_286_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_state5_pp0_stage1_iter1 : BOOLEAN;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal tmp_V_1_reg_403 : STD_LOGIC_VECTOR (10 downto 0);
    signal or_ln47_fu_296_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_V_3_reg_412 : STD_LOGIC_VECTOR (10 downto 0);
    signal i_1_fu_301_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal i_1_reg_417 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal tmp_2_fu_307_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_422 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state7_pp1_stage0_iter0 : BOOLEAN;
    signal ap_block_state9_pp1_stage0_iter1 : BOOLEAN;
    signal ap_block_pp1_stage0_11001 : BOOLEAN;
    signal or_ln36_fu_340_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state8_pp1_stage1_iter0 : BOOLEAN;
    signal ap_block_state10_pp1_stage1_iter1 : BOOLEAN;
    signal ap_block_pp1_stage1_11001 : BOOLEAN;
    signal grp_fu_175_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_V_reg_440 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_enable_reg_pp1_iter0 : STD_LOGIC := '0';
    signal or_ln37_fu_350_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_185_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_V_2_reg_449 : STD_LOGIC_VECTOR (10 downto 0);
    signal i_fu_355_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal i_reg_454 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_block_pp1_stage0_subdone : BOOLEAN;
    signal ap_condition_pp1_exit_iter0_state7 : STD_LOGIC;
    signal ap_block_pp1_stage1_subdone : BOOLEAN;
    signal ap_phi_mux_i1_0_phi_fu_155_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_phi_mux_i_0_phi_fu_167_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln42_fu_265_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln43_fu_276_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln32_fu_319_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln33_fu_330_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ap_block_pp0_stage1_01001 : BOOLEAN;
    signal ap_block_state6 : BOOLEAN;
    signal ap_block_pp1_stage0_01001 : BOOLEAN;
    signal ap_block_pp1_stage1_01001 : BOOLEAN;
    signal icmp_ln25_fu_235_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln25_fu_241_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln40_fu_261_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal or_ln43_fu_270_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln46_fu_281_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_fu_291_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln30_fu_315_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal or_ln33_fu_324_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal compare_node_min_V_fu_205_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln36_fu_335_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal compare_node_max_V_fu_225_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln37_fu_345_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_idle_pp1 : STD_LOGIC;
    signal ap_enable_pp1 : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((not(((ap_start = ap_const_logic_0) or ((ap_const_lv1_1 = and_ln25_fu_241_p2) and (result_V_V_full_n = ap_const_logic_0)))) and (fatherSearch_read_read_fu_84_p2 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln25_fu_241_p2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif ((not(((ap_start = ap_const_logic_0) or ((ap_const_lv1_1 = and_ln25_fu_241_p2) and (result_V_V_full_n = ap_const_logic_0)))) and (fatherSearch_read_read_fu_84_p2 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln25_fu_241_p2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_logic_1 = ap_condition_pp1_exit_iter0_state7))) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
                elsif ((not(((ap_start = ap_const_logic_0) or ((ap_const_lv1_1 = and_ln25_fu_241_p2) and (result_V_V_full_n = ap_const_logic_0)))) and (fatherSearch_read_read_fu_84_p2 = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln25_fu_241_p2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp1_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage1))) then 
                    ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
                elsif ((not(((ap_start = ap_const_logic_0) or ((ap_const_lv1_1 = and_ln25_fu_241_p2) and (result_V_V_full_n = ap_const_logic_0)))) and (fatherSearch_read_read_fu_84_p2 = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln25_fu_241_p2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp1_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i1_0_reg_151_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start = ap_const_logic_0) or ((ap_const_lv1_1 = and_ln25_fu_241_p2) and (result_V_V_full_n = ap_const_logic_0)))) and (fatherSearch_read_read_fu_84_p2 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln25_fu_241_p2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i1_0_reg_151 <= ap_const_lv11_0;
            elsif (((tmp_3_reg_385 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                i1_0_reg_151 <= i_1_reg_417;
            end if; 
        end if;
    end process;

    i_0_reg_163_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start = ap_const_logic_0) or ((ap_const_lv1_1 = and_ln25_fu_241_p2) and (result_V_V_full_n = ap_const_logic_0)))) and (fatherSearch_read_read_fu_84_p2 = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln25_fu_241_p2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_0_reg_163 <= ap_const_lv11_0;
            elsif (((tmp_2_reg_422 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then 
                i_0_reg_163 <= i_reg_454;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start = ap_const_logic_0) or ((ap_const_lv1_1 = and_ln25_fu_241_p2) and (result_V_V_full_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                and_ln25_reg_373 <= and_ln25_fu_241_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_3_reg_385 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                i_1_reg_417 <= i_1_fu_301_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_2_reg_422 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage1) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1))) then
                i_reg_454 <= i_fu_355_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start = ap_const_logic_0) or ((ap_const_lv1_1 = and_ln25_fu_241_p2) and (result_V_V_full_n = ap_const_logic_0)))) and (ap_const_lv1_0 = and_ln25_fu_241_p2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                icmp_ln36_1_reg_377 <= icmp_ln36_1_fu_247_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_2_reg_422 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage1))) then
                or_ln36_reg_436 <= or_ln36_fu_340_p2;
                or_ln37_reg_445 <= or_ln37_fu_350_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_3_reg_385 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                or_ln46_reg_399 <= or_ln46_fu_286_p2;
                or_ln47_reg_408 <= or_ln47_fu_296_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then
                tmp_2_reg_422 <= ap_phi_mux_i_0_phi_fu_167_p4(10 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_3_reg_385 <= ap_phi_mux_i1_0_phi_fu_155_p4(10 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((or_ln46_fu_286_p2 = ap_const_lv1_0) and (tmp_3_reg_385 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                tmp_V_1_reg_403 <= tree_V_q0(12 downto 2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((or_ln37_fu_350_p2 = ap_const_lv1_0) and (tmp_2_reg_422 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage1) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1))) then
                tmp_V_2_reg_449 <= tree_V_q1(23 downto 13);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((or_ln47_fu_296_p2 = ap_const_lv1_0) and (tmp_3_reg_385 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                tmp_V_3_reg_412 <= tree_V_q1(12 downto 2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((or_ln36_fu_340_p2 = ap_const_lv1_0) and (tmp_2_reg_422 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage1) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1))) then
                tmp_V_reg_440 <= tree_V_q0(23 downto 13);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, result_V_V_full_n, and_ln25_fu_241_p2, ap_enable_reg_pp1_iter1, ap_CS_fsm_pp1_stage1, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_CS_fsm_state6, and_ln25_reg_373, fatherSearch_read_read_fu_84_p2, tmp_3_fu_253_p3, ap_enable_reg_pp0_iter0, tmp_2_fu_307_p3, ap_enable_reg_pp1_iter0, ap_block_pp0_stage0_subdone, ap_block_pp0_stage1_subdone, ap_block_pp1_stage0_subdone, ap_block_pp1_stage1_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or ((ap_const_lv1_1 = and_ln25_fu_241_p2) and (result_V_V_full_n = ap_const_logic_0)))) and (ap_const_lv1_1 = and_ln25_fu_241_p2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                elsif ((not(((ap_start = ap_const_logic_0) or ((ap_const_lv1_1 = and_ln25_fu_241_p2) and (result_V_V_full_n = ap_const_logic_0)))) and (fatherSearch_read_read_fu_84_p2 = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln25_fu_241_p2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                elsif ((not(((ap_start = ap_const_logic_0) or ((ap_const_lv1_1 = and_ln25_fu_241_p2) and (result_V_V_full_n = ap_const_logic_0)))) and (fatherSearch_read_read_fu_84_p2 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln25_fu_241_p2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (tmp_3_fu_253_p3 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (tmp_3_fu_253_p3 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((not(((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_state6 => 
                if ((not(((ap_const_lv1_0 = and_ln25_reg_373) and (result_V_V_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_pp1_stage0 => 
                if ((not(((ap_enable_reg_pp1_iter1 = ap_const_logic_0) and (tmp_2_fu_307_p3 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp1_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage1;
                elsif (((ap_enable_reg_pp1_iter1 = ap_const_logic_0) and (tmp_2_fu_307_p3 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                end if;
            when ap_ST_fsm_pp1_stage1 => 
                if ((not(((ap_const_boolean_0 = ap_block_pp1_stage1_subdone) and (ap_enable_reg_pp1_iter0 = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage1) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp1_stage1_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp1_stage1_subdone) and (ap_enable_reg_pp1_iter0 = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage1) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    and_ln25_fu_241_p1 <= (0=>fatherSearch, others=>'-');
    and_ln25_fu_241_p2 <= (icmp_ln25_fu_235_p2 and and_ln25_fu_241_p1);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(2);
    ap_CS_fsm_pp1_stage0 <= ap_CS_fsm(4);
    ap_CS_fsm_pp1_stage1 <= ap_CS_fsm(5);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state6 <= ap_CS_fsm(3);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(result_V_V_full_n, ap_enable_reg_pp0_iter1, or_ln46_reg_399)
    begin
                ap_block_pp0_stage0_01001 <= ((or_ln46_reg_399 = ap_const_lv1_0) and (result_V_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(result_V_V_full_n, ap_enable_reg_pp0_iter1, or_ln46_reg_399)
    begin
                ap_block_pp0_stage0_11001 <= ((or_ln46_reg_399 = ap_const_lv1_0) and (result_V_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(result_V_V_full_n, ap_enable_reg_pp0_iter1, or_ln46_reg_399)
    begin
                ap_block_pp0_stage0_subdone <= ((or_ln46_reg_399 = ap_const_lv1_0) and (result_V_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_01001_assign_proc : process(result_V_V_full_n, ap_enable_reg_pp0_iter1, or_ln47_reg_408)
    begin
                ap_block_pp0_stage1_01001 <= ((or_ln47_reg_408 = ap_const_lv1_0) and (result_V_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage1_11001_assign_proc : process(result_V_V_full_n, ap_enable_reg_pp0_iter1, or_ln47_reg_408)
    begin
                ap_block_pp0_stage1_11001 <= ((or_ln47_reg_408 = ap_const_lv1_0) and (result_V_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage1_subdone_assign_proc : process(result_V_V_full_n, ap_enable_reg_pp0_iter1, or_ln47_reg_408)
    begin
                ap_block_pp0_stage1_subdone <= ((or_ln47_reg_408 = ap_const_lv1_0) and (result_V_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp1_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp1_stage0_01001_assign_proc : process(result_V_V_full_n, ap_enable_reg_pp1_iter1, or_ln36_reg_436)
    begin
                ap_block_pp1_stage0_01001 <= ((or_ln36_reg_436 = ap_const_lv1_0) and (result_V_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp1_stage0_11001_assign_proc : process(result_V_V_full_n, ap_enable_reg_pp1_iter1, or_ln36_reg_436)
    begin
                ap_block_pp1_stage0_11001 <= ((or_ln36_reg_436 = ap_const_lv1_0) and (result_V_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp1_stage0_subdone_assign_proc : process(result_V_V_full_n, ap_enable_reg_pp1_iter1, or_ln36_reg_436)
    begin
                ap_block_pp1_stage0_subdone <= ((or_ln36_reg_436 = ap_const_lv1_0) and (result_V_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp1_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp1_stage1_01001_assign_proc : process(result_V_V_full_n, ap_enable_reg_pp1_iter1, or_ln37_reg_445)
    begin
                ap_block_pp1_stage1_01001 <= ((or_ln37_reg_445 = ap_const_lv1_0) and (result_V_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp1_stage1_11001_assign_proc : process(result_V_V_full_n, ap_enable_reg_pp1_iter1, or_ln37_reg_445)
    begin
                ap_block_pp1_stage1_11001 <= ((or_ln37_reg_445 = ap_const_lv1_0) and (result_V_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp1_stage1_subdone_assign_proc : process(result_V_V_full_n, ap_enable_reg_pp1_iter1, or_ln37_reg_445)
    begin
                ap_block_pp1_stage1_subdone <= ((or_ln37_reg_445 = ap_const_lv1_0) and (result_V_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1));
    end process;


    ap_block_state1_assign_proc : process(ap_start, result_V_V_full_n, and_ln25_fu_241_p2)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or ((ap_const_lv1_1 = and_ln25_fu_241_p2) and (result_V_V_full_n = ap_const_logic_0)));
    end process;


    ap_block_state10_pp1_stage1_iter1_assign_proc : process(result_V_V_full_n, or_ln37_reg_445)
    begin
                ap_block_state10_pp1_stage1_iter1 <= ((or_ln37_reg_445 = ap_const_lv1_0) and (result_V_V_full_n = ap_const_logic_0));
    end process;

        ap_block_state2_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state4_pp0_stage0_iter1_assign_proc : process(result_V_V_full_n, or_ln46_reg_399)
    begin
                ap_block_state4_pp0_stage0_iter1 <= ((or_ln46_reg_399 = ap_const_lv1_0) and (result_V_V_full_n = ap_const_logic_0));
    end process;


    ap_block_state5_pp0_stage1_iter1_assign_proc : process(result_V_V_full_n, or_ln47_reg_408)
    begin
                ap_block_state5_pp0_stage1_iter1 <= ((or_ln47_reg_408 = ap_const_lv1_0) and (result_V_V_full_n = ap_const_logic_0));
    end process;


    ap_block_state6_assign_proc : process(result_V_V_full_n, and_ln25_reg_373)
    begin
                ap_block_state6 <= ((ap_const_lv1_0 = and_ln25_reg_373) and (result_V_V_full_n = ap_const_logic_0));
    end process;

        ap_block_state7_pp1_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp1_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state9_pp1_stage0_iter1_assign_proc : process(result_V_V_full_n, or_ln36_reg_436)
    begin
                ap_block_state9_pp1_stage0_iter1 <= ((or_ln36_reg_436 = ap_const_lv1_0) and (result_V_V_full_n = ap_const_logic_0));
    end process;


    ap_condition_pp0_exit_iter0_state2_assign_proc : process(tmp_3_fu_253_p3)
    begin
        if ((tmp_3_fu_253_p3 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_pp1_exit_iter0_state7_assign_proc : process(tmp_2_fu_307_p3)
    begin
        if ((tmp_2_fu_307_p3 = ap_const_lv1_1)) then 
            ap_condition_pp1_exit_iter0_state7 <= ap_const_logic_1;
        else 
            ap_condition_pp1_exit_iter0_state7 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, result_V_V_full_n, ap_CS_fsm_state6, and_ln25_reg_373)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or (not(((ap_const_lv1_0 = and_ln25_reg_373) and (result_V_V_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_pp1 <= (ap_idle_pp1 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp1_assign_proc : process(ap_enable_reg_pp1_iter1, ap_enable_reg_pp1_iter0)
    begin
        if (((ap_enable_reg_pp1_iter1 = ap_const_logic_0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_0))) then 
            ap_idle_pp1 <= ap_const_logic_1;
        else 
            ap_idle_pp1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_i1_0_phi_fu_155_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, i1_0_reg_151, tmp_3_reg_385, i_1_reg_417)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (tmp_3_reg_385 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_phi_mux_i1_0_phi_fu_155_p4 <= i_1_reg_417;
        else 
            ap_phi_mux_i1_0_phi_fu_155_p4 <= i1_0_reg_151;
        end if; 
    end process;


    ap_phi_mux_i_0_phi_fu_167_p4_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, i_0_reg_163, tmp_2_reg_422, i_reg_454)
    begin
        if (((tmp_2_reg_422 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            ap_phi_mux_i_0_phi_fu_167_p4 <= i_reg_454;
        else 
            ap_phi_mux_i_0_phi_fu_167_p4 <= i_0_reg_163;
        end if; 
    end process;


    ap_ready_assign_proc : process(result_V_V_full_n, ap_CS_fsm_state6, and_ln25_reg_373)
    begin
        if ((not(((ap_const_lv1_0 = and_ln25_reg_373) and (result_V_V_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    compare_node_max_V_fu_225_p4 <= tree_V_q1(12 downto 2);
    compare_node_min_V_fu_205_p4 <= tree_V_q0(12 downto 2);
    fatherSearch_read_read_fu_84_p2 <= (0=>fatherSearch, others=>'-');
    grp_fu_175_p4 <= tree_V_q0(23 downto 13);
    grp_fu_185_p4 <= tree_V_q1(23 downto 13);
    i_1_fu_301_p2 <= std_logic_vector(unsigned(i1_0_reg_151) + unsigned(ap_const_lv11_2));
    i_fu_355_p2 <= std_logic_vector(unsigned(i_0_reg_163) + unsigned(ap_const_lv11_2));
    icmp_ln25_fu_235_p2 <= "1" when (nodo_V = ap_const_lv11_1) else "0";
    icmp_ln36_1_fu_247_p2 <= "0" when (relationship_V = ap_const_lv2_0) else "1";
    icmp_ln36_fu_335_p2 <= "0" when (compare_node_min_V_fu_205_p4 = nodo_V) else "1";
    icmp_ln37_fu_345_p2 <= "0" when (compare_node_max_V_fu_225_p4 = nodo_V) else "1";
    icmp_ln46_fu_281_p2 <= "0" when (grp_fu_175_p4 = nodo_V) else "1";
    icmp_ln47_fu_291_p2 <= "0" when (grp_fu_185_p4 = nodo_V) else "1";
    or_ln33_fu_324_p2 <= (trunc_ln30_fu_315_p1 or ap_const_lv10_1);
    or_ln36_fu_340_p2 <= (icmp_ln36_fu_335_p2 or icmp_ln36_1_reg_377);
    or_ln37_fu_350_p2 <= (icmp_ln37_fu_345_p2 or icmp_ln36_1_reg_377);
    or_ln43_fu_270_p2 <= (trunc_ln40_fu_261_p1 or ap_const_lv10_1);
    or_ln46_fu_286_p2 <= (icmp_ln46_fu_281_p2 or icmp_ln36_1_reg_377);
    or_ln47_fu_296_p2 <= (icmp_ln47_fu_291_p2 or icmp_ln36_1_reg_377);

    result_V_V_blk_n_assign_proc : process(ap_start, ap_CS_fsm_state1, result_V_V_full_n, and_ln25_fu_241_p2, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, or_ln36_reg_436, ap_CS_fsm_pp1_stage1, ap_block_pp1_stage1, or_ln37_reg_445, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, or_ln46_reg_399, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, or_ln47_reg_408, ap_CS_fsm_state6, and_ln25_reg_373)
    begin
        if ((((or_ln47_reg_408 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (or_ln46_reg_399 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp1_stage1) and (or_ln37_reg_445 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage1) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1)) or ((or_ln36_reg_436 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0)) or ((ap_const_lv1_1 = and_ln25_fu_241_p2) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)) or ((ap_const_lv1_0 = and_ln25_reg_373) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            result_V_V_blk_n <= result_V_V_full_n;
        else 
            result_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    result_V_V_din_assign_proc : process(ap_start, ap_CS_fsm_state1, result_V_V_full_n, and_ln25_fu_241_p2, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, or_ln36_reg_436, ap_CS_fsm_pp1_stage1, or_ln37_reg_445, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, or_ln46_reg_399, ap_CS_fsm_pp0_stage1, or_ln47_reg_408, ap_CS_fsm_state6, and_ln25_reg_373, tmp_V_1_reg_403, tmp_V_3_reg_412, tmp_V_reg_440, tmp_V_2_reg_449, ap_block_pp0_stage0_01001, ap_block_pp0_stage1_01001, ap_block_pp1_stage0_01001, ap_block_pp1_stage1_01001)
    begin
        if (((or_ln37_reg_445 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage1_01001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage1) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1))) then 
            result_V_V_din <= tmp_V_2_reg_449;
        elsif (((or_ln36_reg_436 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0_01001) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            result_V_V_din <= tmp_V_reg_440;
        elsif (((or_ln47_reg_408 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_01001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            result_V_V_din <= tmp_V_3_reg_412;
        elsif (((or_ln46_reg_399 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            result_V_V_din <= tmp_V_1_reg_403;
        elsif (((not(((ap_start = ap_const_logic_0) or ((ap_const_lv1_1 = and_ln25_fu_241_p2) and (result_V_V_full_n = ap_const_logic_0)))) and (ap_const_lv1_1 = and_ln25_fu_241_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or (not(((ap_const_lv1_0 = and_ln25_reg_373) and (result_V_V_full_n = ap_const_logic_0))) and (ap_const_lv1_0 = and_ln25_reg_373) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            result_V_V_din <= ap_const_lv11_0;
        else 
            result_V_V_din <= "XXXXXXXXXXX";
        end if; 
    end process;


    result_V_V_write_assign_proc : process(ap_start, ap_CS_fsm_state1, result_V_V_full_n, and_ln25_fu_241_p2, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, or_ln36_reg_436, ap_CS_fsm_pp1_stage1, or_ln37_reg_445, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, or_ln46_reg_399, ap_CS_fsm_pp0_stage1, or_ln47_reg_408, ap_CS_fsm_state6, and_ln25_reg_373, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001, ap_block_pp1_stage0_11001, ap_block_pp1_stage1_11001)
    begin
        if ((((or_ln47_reg_408 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)) or ((or_ln46_reg_399 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((or_ln37_reg_445 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage1) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1)) or ((or_ln36_reg_436 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001)) or (not(((ap_start = ap_const_logic_0) or ((ap_const_lv1_1 = and_ln25_fu_241_p2) and (result_V_V_full_n = ap_const_logic_0)))) and (ap_const_lv1_1 = and_ln25_fu_241_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or (not(((ap_const_lv1_0 = and_ln25_reg_373) and (result_V_V_full_n = ap_const_logic_0))) and (ap_const_lv1_0 = and_ln25_reg_373) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            result_V_V_write <= ap_const_logic_1;
        else 
            result_V_V_write <= ap_const_logic_0;
        end if; 
    end process;

    tmp_2_fu_307_p3 <= ap_phi_mux_i_0_phi_fu_167_p4(10 downto 10);
    tmp_3_fu_253_p3 <= ap_phi_mux_i1_0_phi_fu_155_p4(10 downto 10);

    tree_V_address0_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_block_pp1_stage0, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp1_iter0, zext_ln42_fu_265_p1, zext_ln32_fu_319_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1))) then 
            tree_V_address0 <= zext_ln32_fu_319_p1(10 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
            tree_V_address0 <= zext_ln42_fu_265_p1(10 - 1 downto 0);
        else 
            tree_V_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    tree_V_address1_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_block_pp1_stage0, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp1_iter0, zext_ln43_fu_276_p1, zext_ln33_fu_330_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1))) then 
            tree_V_address1 <= zext_ln33_fu_330_p1(10 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
            tree_V_address1 <= zext_ln43_fu_276_p1(10 - 1 downto 0);
        else 
            tree_V_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    tree_V_ce0_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0, ap_block_pp1_stage0_11001, ap_enable_reg_pp1_iter0)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001)))) then 
            tree_V_ce0 <= ap_const_logic_1;
        else 
            tree_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    tree_V_ce1_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0, ap_block_pp1_stage0_11001, ap_enable_reg_pp1_iter0)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001)))) then 
            tree_V_ce1 <= ap_const_logic_1;
        else 
            tree_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln30_fu_315_p1 <= ap_phi_mux_i_0_phi_fu_167_p4(10 - 1 downto 0);
    trunc_ln40_fu_261_p1 <= ap_phi_mux_i1_0_phi_fu_155_p4(10 - 1 downto 0);
    zext_ln32_fu_319_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_i_0_phi_fu_167_p4),64));
    zext_ln33_fu_330_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln33_fu_324_p2),64));
    zext_ln42_fu_265_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_i1_0_phi_fu_155_p4),64));
    zext_ln43_fu_276_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln43_fu_270_p2),64));
end behav;
