// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "busqueda_cam.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic busqueda_cam::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic busqueda_cam::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<6> busqueda_cam::ap_ST_fsm_state1 = "1";
const sc_lv<6> busqueda_cam::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<6> busqueda_cam::ap_ST_fsm_pp0_stage1 = "100";
const sc_lv<6> busqueda_cam::ap_ST_fsm_state6 = "1000";
const sc_lv<6> busqueda_cam::ap_ST_fsm_pp1_stage0 = "10000";
const sc_lv<6> busqueda_cam::ap_ST_fsm_pp1_stage1 = "100000";
const bool busqueda_cam::ap_const_boolean_1 = true;
const sc_lv<32> busqueda_cam::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> busqueda_cam::ap_const_lv1_1 = "1";
const sc_lv<32> busqueda_cam::ap_const_lv32_4 = "100";
const bool busqueda_cam::ap_const_boolean_0 = false;
const sc_lv<1> busqueda_cam::ap_const_lv1_0 = "0";
const sc_lv<32> busqueda_cam::ap_const_lv32_5 = "101";
const sc_lv<32> busqueda_cam::ap_const_lv32_1 = "1";
const sc_lv<32> busqueda_cam::ap_const_lv32_2 = "10";
const sc_lv<32> busqueda_cam::ap_const_lv32_3 = "11";
const sc_lv<11> busqueda_cam::ap_const_lv11_0 = "00000000000";
const sc_lv<32> busqueda_cam::ap_const_lv32_D = "1101";
const sc_lv<32> busqueda_cam::ap_const_lv32_17 = "10111";
const sc_lv<32> busqueda_cam::ap_const_lv32_C = "1100";
const sc_lv<11> busqueda_cam::ap_const_lv11_1 = "1";
const sc_lv<2> busqueda_cam::ap_const_lv2_0 = "00";
const sc_lv<32> busqueda_cam::ap_const_lv32_A = "1010";
const sc_lv<10> busqueda_cam::ap_const_lv10_1 = "1";
const sc_lv<11> busqueda_cam::ap_const_lv11_2 = "10";

busqueda_cam::busqueda_cam(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_and_ln25_fu_241_p1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( fatherSearch );

    SC_METHOD(thread_and_ln25_fu_241_p2);
    sensitive << ( icmp_ln25_fu_235_p2 );
    sensitive << ( and_ln25_fu_241_p1 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp1_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp1_stage1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( result_V_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( or_ln46_reg_399 );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( result_V_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( or_ln46_reg_399 );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( result_V_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( or_ln46_reg_399 );

    SC_METHOD(thread_ap_block_pp0_stage1);

    SC_METHOD(thread_ap_block_pp0_stage1_01001);
    sensitive << ( result_V_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( or_ln47_reg_408 );

    SC_METHOD(thread_ap_block_pp0_stage1_11001);
    sensitive << ( result_V_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( or_ln47_reg_408 );

    SC_METHOD(thread_ap_block_pp0_stage1_subdone);
    sensitive << ( result_V_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( or_ln47_reg_408 );

    SC_METHOD(thread_ap_block_pp1_stage0);

    SC_METHOD(thread_ap_block_pp1_stage0_01001);
    sensitive << ( result_V_V_full_n );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( or_ln36_reg_436 );

    SC_METHOD(thread_ap_block_pp1_stage0_11001);
    sensitive << ( result_V_V_full_n );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( or_ln36_reg_436 );

    SC_METHOD(thread_ap_block_pp1_stage0_subdone);
    sensitive << ( result_V_V_full_n );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( or_ln36_reg_436 );

    SC_METHOD(thread_ap_block_pp1_stage1);

    SC_METHOD(thread_ap_block_pp1_stage1_01001);
    sensitive << ( result_V_V_full_n );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( or_ln37_reg_445 );

    SC_METHOD(thread_ap_block_pp1_stage1_11001);
    sensitive << ( result_V_V_full_n );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( or_ln37_reg_445 );

    SC_METHOD(thread_ap_block_pp1_stage1_subdone);
    sensitive << ( result_V_V_full_n );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( or_ln37_reg_445 );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( result_V_V_full_n );
    sensitive << ( and_ln25_fu_241_p2 );

    SC_METHOD(thread_ap_block_state10_pp1_stage1_iter1);
    sensitive << ( result_V_V_full_n );
    sensitive << ( or_ln37_reg_445 );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage1_iter0);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter1);
    sensitive << ( result_V_V_full_n );
    sensitive << ( or_ln46_reg_399 );

    SC_METHOD(thread_ap_block_state5_pp0_stage1_iter1);
    sensitive << ( result_V_V_full_n );
    sensitive << ( or_ln47_reg_408 );

    SC_METHOD(thread_ap_block_state6);
    sensitive << ( result_V_V_full_n );
    sensitive << ( and_ln25_reg_373 );

    SC_METHOD(thread_ap_block_state7_pp1_stage0_iter0);

    SC_METHOD(thread_ap_block_state8_pp1_stage1_iter0);

    SC_METHOD(thread_ap_block_state9_pp1_stage0_iter1);
    sensitive << ( result_V_V_full_n );
    sensitive << ( or_ln36_reg_436 );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( tmp_3_fu_253_p3 );

    SC_METHOD(thread_ap_condition_pp1_exit_iter0_state7);
    sensitive << ( tmp_2_fu_307_p3 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( result_V_V_full_n );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( and_ln25_reg_373 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_pp1);
    sensitive << ( ap_idle_pp1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_idle_pp1);
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_ap_phi_mux_i1_0_phi_fu_155_p4);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( i1_0_reg_151 );
    sensitive << ( tmp_3_reg_385 );
    sensitive << ( i_1_reg_417 );

    SC_METHOD(thread_ap_phi_mux_i_0_phi_fu_167_p4);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( i_0_reg_163 );
    sensitive << ( tmp_2_reg_422 );
    sensitive << ( i_reg_454 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( result_V_V_full_n );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( and_ln25_reg_373 );

    SC_METHOD(thread_compare_node_max_V_fu_225_p4);
    sensitive << ( tree_V_q1 );

    SC_METHOD(thread_compare_node_min_V_fu_205_p4);
    sensitive << ( tree_V_q0 );

    SC_METHOD(thread_fatherSearch_read_read_fu_84_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( fatherSearch );
    sensitive << ( result_V_V_full_n );
    sensitive << ( and_ln25_fu_241_p2 );

    SC_METHOD(thread_grp_fu_175_p4);
    sensitive << ( tree_V_q0 );

    SC_METHOD(thread_grp_fu_185_p4);
    sensitive << ( tree_V_q1 );

    SC_METHOD(thread_i_1_fu_301_p2);
    sensitive << ( i1_0_reg_151 );

    SC_METHOD(thread_i_fu_355_p2);
    sensitive << ( i_0_reg_163 );

    SC_METHOD(thread_icmp_ln25_fu_235_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( nodo_V );
    sensitive << ( result_V_V_full_n );
    sensitive << ( and_ln25_fu_241_p2 );

    SC_METHOD(thread_icmp_ln36_1_fu_247_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( relationship_V );
    sensitive << ( result_V_V_full_n );
    sensitive << ( and_ln25_fu_241_p2 );

    SC_METHOD(thread_icmp_ln36_fu_335_p2);
    sensitive << ( nodo_V );
    sensitive << ( ap_CS_fsm_pp1_stage1 );
    sensitive << ( tmp_2_reg_422 );
    sensitive << ( ap_block_pp1_stage1_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( compare_node_min_V_fu_205_p4 );

    SC_METHOD(thread_icmp_ln37_fu_345_p2);
    sensitive << ( nodo_V );
    sensitive << ( ap_CS_fsm_pp1_stage1 );
    sensitive << ( tmp_2_reg_422 );
    sensitive << ( ap_block_pp1_stage1_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( compare_node_max_V_fu_225_p4 );

    SC_METHOD(thread_icmp_ln46_fu_281_p2);
    sensitive << ( nodo_V );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( tmp_3_reg_385 );
    sensitive << ( ap_block_pp0_stage1_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( grp_fu_175_p4 );

    SC_METHOD(thread_icmp_ln47_fu_291_p2);
    sensitive << ( nodo_V );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( tmp_3_reg_385 );
    sensitive << ( ap_block_pp0_stage1_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( grp_fu_185_p4 );

    SC_METHOD(thread_or_ln33_fu_324_p2);
    sensitive << ( trunc_ln30_fu_315_p1 );

    SC_METHOD(thread_or_ln36_fu_340_p2);
    sensitive << ( icmp_ln36_1_reg_377 );
    sensitive << ( icmp_ln36_fu_335_p2 );

    SC_METHOD(thread_or_ln37_fu_350_p2);
    sensitive << ( icmp_ln36_1_reg_377 );
    sensitive << ( icmp_ln37_fu_345_p2 );

    SC_METHOD(thread_or_ln43_fu_270_p2);
    sensitive << ( trunc_ln40_fu_261_p1 );

    SC_METHOD(thread_or_ln46_fu_286_p2);
    sensitive << ( icmp_ln36_1_reg_377 );
    sensitive << ( icmp_ln46_fu_281_p2 );

    SC_METHOD(thread_or_ln47_fu_296_p2);
    sensitive << ( icmp_ln36_1_reg_377 );
    sensitive << ( icmp_ln47_fu_291_p2 );

    SC_METHOD(thread_result_V_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( result_V_V_full_n );
    sensitive << ( and_ln25_fu_241_p2 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( or_ln36_reg_436 );
    sensitive << ( ap_CS_fsm_pp1_stage1 );
    sensitive << ( ap_block_pp1_stage1 );
    sensitive << ( or_ln37_reg_445 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( or_ln46_reg_399 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( or_ln47_reg_408 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( and_ln25_reg_373 );

    SC_METHOD(thread_result_V_V_din);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( result_V_V_full_n );
    sensitive << ( and_ln25_fu_241_p2 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( or_ln36_reg_436 );
    sensitive << ( ap_CS_fsm_pp1_stage1 );
    sensitive << ( or_ln37_reg_445 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( or_ln46_reg_399 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( or_ln47_reg_408 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( and_ln25_reg_373 );
    sensitive << ( tmp_V_1_reg_403 );
    sensitive << ( tmp_V_3_reg_412 );
    sensitive << ( tmp_V_reg_440 );
    sensitive << ( tmp_V_2_reg_449 );
    sensitive << ( ap_block_pp0_stage0_01001 );
    sensitive << ( ap_block_pp0_stage1_01001 );
    sensitive << ( ap_block_pp1_stage0_01001 );
    sensitive << ( ap_block_pp1_stage1_01001 );

    SC_METHOD(thread_result_V_V_write);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( result_V_V_full_n );
    sensitive << ( and_ln25_fu_241_p2 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( or_ln36_reg_436 );
    sensitive << ( ap_CS_fsm_pp1_stage1 );
    sensitive << ( or_ln37_reg_445 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( or_ln46_reg_399 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( or_ln47_reg_408 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( and_ln25_reg_373 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_block_pp0_stage1_11001 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_block_pp1_stage1_11001 );

    SC_METHOD(thread_tmp_2_fu_307_p3);
    sensitive << ( ap_phi_mux_i_0_phi_fu_167_p4 );

    SC_METHOD(thread_tmp_3_fu_253_p3);
    sensitive << ( ap_phi_mux_i1_0_phi_fu_155_p4 );

    SC_METHOD(thread_tree_V_address0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( zext_ln42_fu_265_p1 );
    sensitive << ( zext_ln32_fu_319_p1 );

    SC_METHOD(thread_tree_V_address1);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( zext_ln43_fu_276_p1 );
    sensitive << ( zext_ln33_fu_330_p1 );

    SC_METHOD(thread_tree_V_ce0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_tree_V_ce1);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_trunc_ln30_fu_315_p1);
    sensitive << ( ap_phi_mux_i_0_phi_fu_167_p4 );

    SC_METHOD(thread_trunc_ln40_fu_261_p1);
    sensitive << ( ap_phi_mux_i1_0_phi_fu_155_p4 );

    SC_METHOD(thread_zext_ln32_fu_319_p1);
    sensitive << ( ap_phi_mux_i_0_phi_fu_167_p4 );

    SC_METHOD(thread_zext_ln33_fu_330_p1);
    sensitive << ( or_ln33_fu_324_p2 );

    SC_METHOD(thread_zext_ln42_fu_265_p1);
    sensitive << ( ap_phi_mux_i1_0_phi_fu_155_p4 );

    SC_METHOD(thread_zext_ln43_fu_276_p1);
    sensitive << ( or_ln43_fu_270_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( result_V_V_full_n );
    sensitive << ( and_ln25_fu_241_p2 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_CS_fsm_pp1_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( and_ln25_reg_373 );
    sensitive << ( fatherSearch_read_read_fu_84_p2 );
    sensitive << ( tmp_3_fu_253_p3 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( tmp_2_fu_307_p3 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_block_pp0_stage1_subdone );
    sensitive << ( ap_block_pp1_stage0_subdone );
    sensitive << ( ap_block_pp1_stage1_subdone );

    ap_CS_fsm = "000001";
    ap_enable_reg_pp1_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter0 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "busqueda_cam_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, tree_V_address0, "(port)tree_V_address0");
    sc_trace(mVcdFile, tree_V_ce0, "(port)tree_V_ce0");
    sc_trace(mVcdFile, tree_V_q0, "(port)tree_V_q0");
    sc_trace(mVcdFile, tree_V_address1, "(port)tree_V_address1");
    sc_trace(mVcdFile, tree_V_ce1, "(port)tree_V_ce1");
    sc_trace(mVcdFile, tree_V_q1, "(port)tree_V_q1");
    sc_trace(mVcdFile, nodo_V, "(port)nodo_V");
    sc_trace(mVcdFile, relationship_V, "(port)relationship_V");
    sc_trace(mVcdFile, fatherSearch, "(port)fatherSearch");
    sc_trace(mVcdFile, result_V_V_din, "(port)result_V_V_din");
    sc_trace(mVcdFile, result_V_V_full_n, "(port)result_V_V_full_n");
    sc_trace(mVcdFile, result_V_V_write, "(port)result_V_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, result_V_V_blk_n, "result_V_V_blk_n");
    sc_trace(mVcdFile, and_ln25_fu_241_p2, "and_ln25_fu_241_p2");
    sc_trace(mVcdFile, ap_CS_fsm_pp1_stage0, "ap_CS_fsm_pp1_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter1, "ap_enable_reg_pp1_iter1");
    sc_trace(mVcdFile, ap_block_pp1_stage0, "ap_block_pp1_stage0");
    sc_trace(mVcdFile, or_ln36_reg_436, "or_ln36_reg_436");
    sc_trace(mVcdFile, ap_CS_fsm_pp1_stage1, "ap_CS_fsm_pp1_stage1");
    sc_trace(mVcdFile, ap_block_pp1_stage1, "ap_block_pp1_stage1");
    sc_trace(mVcdFile, or_ln37_reg_445, "or_ln37_reg_445");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, or_ln46_reg_399, "or_ln46_reg_399");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage1, "ap_CS_fsm_pp0_stage1");
    sc_trace(mVcdFile, ap_block_pp0_stage1, "ap_block_pp0_stage1");
    sc_trace(mVcdFile, or_ln47_reg_408, "or_ln47_reg_408");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, and_ln25_reg_373, "and_ln25_reg_373");
    sc_trace(mVcdFile, i1_0_reg_151, "i1_0_reg_151");
    sc_trace(mVcdFile, i_0_reg_163, "i_0_reg_163");
    sc_trace(mVcdFile, fatherSearch_read_read_fu_84_p2, "fatherSearch_read_read_fu_84_p2");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, icmp_ln36_1_fu_247_p2, "icmp_ln36_1_fu_247_p2");
    sc_trace(mVcdFile, icmp_ln36_1_reg_377, "icmp_ln36_1_reg_377");
    sc_trace(mVcdFile, tmp_3_fu_253_p3, "tmp_3_fu_253_p3");
    sc_trace(mVcdFile, tmp_3_reg_385, "tmp_3_reg_385");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter1, "ap_block_state4_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, or_ln46_fu_286_p2, "or_ln46_fu_286_p2");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage1_iter0, "ap_block_state3_pp0_stage1_iter0");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage1_iter1, "ap_block_state5_pp0_stage1_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage1_11001, "ap_block_pp0_stage1_11001");
    sc_trace(mVcdFile, tmp_V_1_reg_403, "tmp_V_1_reg_403");
    sc_trace(mVcdFile, or_ln47_fu_296_p2, "or_ln47_fu_296_p2");
    sc_trace(mVcdFile, tmp_V_3_reg_412, "tmp_V_3_reg_412");
    sc_trace(mVcdFile, i_1_fu_301_p2, "i_1_fu_301_p2");
    sc_trace(mVcdFile, i_1_reg_417, "i_1_reg_417");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, tmp_2_fu_307_p3, "tmp_2_fu_307_p3");
    sc_trace(mVcdFile, tmp_2_reg_422, "tmp_2_reg_422");
    sc_trace(mVcdFile, ap_block_state7_pp1_stage0_iter0, "ap_block_state7_pp1_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state9_pp1_stage0_iter1, "ap_block_state9_pp1_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp1_stage0_11001, "ap_block_pp1_stage0_11001");
    sc_trace(mVcdFile, or_ln36_fu_340_p2, "or_ln36_fu_340_p2");
    sc_trace(mVcdFile, ap_block_state8_pp1_stage1_iter0, "ap_block_state8_pp1_stage1_iter0");
    sc_trace(mVcdFile, ap_block_state10_pp1_stage1_iter1, "ap_block_state10_pp1_stage1_iter1");
    sc_trace(mVcdFile, ap_block_pp1_stage1_11001, "ap_block_pp1_stage1_11001");
    sc_trace(mVcdFile, grp_fu_175_p4, "grp_fu_175_p4");
    sc_trace(mVcdFile, tmp_V_reg_440, "tmp_V_reg_440");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter0, "ap_enable_reg_pp1_iter0");
    sc_trace(mVcdFile, or_ln37_fu_350_p2, "or_ln37_fu_350_p2");
    sc_trace(mVcdFile, grp_fu_185_p4, "grp_fu_185_p4");
    sc_trace(mVcdFile, tmp_V_2_reg_449, "tmp_V_2_reg_449");
    sc_trace(mVcdFile, i_fu_355_p2, "i_fu_355_p2");
    sc_trace(mVcdFile, i_reg_454, "i_reg_454");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_block_pp0_stage1_subdone, "ap_block_pp0_stage1_subdone");
    sc_trace(mVcdFile, ap_block_pp1_stage0_subdone, "ap_block_pp1_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp1_exit_iter0_state7, "ap_condition_pp1_exit_iter0_state7");
    sc_trace(mVcdFile, ap_block_pp1_stage1_subdone, "ap_block_pp1_stage1_subdone");
    sc_trace(mVcdFile, ap_phi_mux_i1_0_phi_fu_155_p4, "ap_phi_mux_i1_0_phi_fu_155_p4");
    sc_trace(mVcdFile, ap_phi_mux_i_0_phi_fu_167_p4, "ap_phi_mux_i_0_phi_fu_167_p4");
    sc_trace(mVcdFile, zext_ln42_fu_265_p1, "zext_ln42_fu_265_p1");
    sc_trace(mVcdFile, zext_ln43_fu_276_p1, "zext_ln43_fu_276_p1");
    sc_trace(mVcdFile, zext_ln32_fu_319_p1, "zext_ln32_fu_319_p1");
    sc_trace(mVcdFile, zext_ln33_fu_330_p1, "zext_ln33_fu_330_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, ap_block_pp0_stage1_01001, "ap_block_pp0_stage1_01001");
    sc_trace(mVcdFile, ap_block_state6, "ap_block_state6");
    sc_trace(mVcdFile, ap_block_pp1_stage0_01001, "ap_block_pp1_stage0_01001");
    sc_trace(mVcdFile, ap_block_pp1_stage1_01001, "ap_block_pp1_stage1_01001");
    sc_trace(mVcdFile, icmp_ln25_fu_235_p2, "icmp_ln25_fu_235_p2");
    sc_trace(mVcdFile, and_ln25_fu_241_p1, "and_ln25_fu_241_p1");
    sc_trace(mVcdFile, trunc_ln40_fu_261_p1, "trunc_ln40_fu_261_p1");
    sc_trace(mVcdFile, or_ln43_fu_270_p2, "or_ln43_fu_270_p2");
    sc_trace(mVcdFile, icmp_ln46_fu_281_p2, "icmp_ln46_fu_281_p2");
    sc_trace(mVcdFile, icmp_ln47_fu_291_p2, "icmp_ln47_fu_291_p2");
    sc_trace(mVcdFile, trunc_ln30_fu_315_p1, "trunc_ln30_fu_315_p1");
    sc_trace(mVcdFile, or_ln33_fu_324_p2, "or_ln33_fu_324_p2");
    sc_trace(mVcdFile, compare_node_min_V_fu_205_p4, "compare_node_min_V_fu_205_p4");
    sc_trace(mVcdFile, icmp_ln36_fu_335_p2, "icmp_ln36_fu_335_p2");
    sc_trace(mVcdFile, compare_node_max_V_fu_225_p4, "compare_node_max_V_fu_225_p4");
    sc_trace(mVcdFile, icmp_ln37_fu_345_p2, "icmp_ln37_fu_345_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, ap_idle_pp1, "ap_idle_pp1");
    sc_trace(mVcdFile, ap_enable_pp1, "ap_enable_pp1");
#endif

    }
}

busqueda_cam::~busqueda_cam() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void busqueda_cam::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || (esl_seteq<1,1,1>(and_ln25_fu_241_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, result_V_V_full_n.read()))) && 
                    esl_seteq<1,1,1>(and_ln25_fu_241_p2.read(), ap_const_lv1_0) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, fatherSearch_read_read_fu_84_p2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || (esl_seteq<1,1,1>(and_ln25_fu_241_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, result_V_V_full_n.read()))) && 
                    esl_seteq<1,1,1>(and_ln25_fu_241_p2.read(), ap_const_lv1_0) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, fatherSearch_read_read_fu_84_p2.read()))) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp1_exit_iter0_state7.read()))) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || (esl_seteq<1,1,1>(and_ln25_fu_241_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, result_V_V_full_n.read()))) && 
                    esl_seteq<1,1,1>(and_ln25_fu_241_p2.read(), ap_const_lv1_0) && 
                    esl_seteq<1,1,1>(ap_const_lv1_1, fatherSearch_read_read_fu_84_p2.read()))) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage1.read()) && 
             esl_seteq<1,1,1>(ap_block_pp1_stage1_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp1_iter1 = ap_enable_reg_pp1_iter0.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || (esl_seteq<1,1,1>(and_ln25_fu_241_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, result_V_V_full_n.read()))) && 
                    esl_seteq<1,1,1>(and_ln25_fu_241_p2.read(), ap_const_lv1_0) && 
                    esl_seteq<1,1,1>(ap_const_lv1_1, fatherSearch_read_read_fu_84_p2.read()))) {
            ap_enable_reg_pp1_iter1 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || (esl_seteq<1,1,1>(and_ln25_fu_241_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, result_V_V_full_n.read()))) && 
         esl_seteq<1,1,1>(and_ln25_fu_241_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, fatherSearch_read_read_fu_84_p2.read()))) {
        i1_0_reg_151 = ap_const_lv11_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_reg_385.read()))) {
        i1_0_reg_151 = i_1_reg_417.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || (esl_seteq<1,1,1>(and_ln25_fu_241_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, result_V_V_full_n.read()))) && 
         esl_seteq<1,1,1>(and_ln25_fu_241_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, fatherSearch_read_read_fu_84_p2.read()))) {
        i_0_reg_163 = ap_const_lv11_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
                esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_2_reg_422.read()))) {
        i_0_reg_163 = i_reg_454.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || (esl_seteq<1,1,1>(and_ln25_fu_241_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, result_V_V_full_n.read()))))) {
        and_ln25_reg_373 = and_ln25_fu_241_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_reg_385.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        i_1_reg_417 = i_1_fu_301_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage1_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_2_reg_422.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()))) {
        i_reg_454 = i_fu_355_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || (esl_seteq<1,1,1>(and_ln25_fu_241_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, result_V_V_full_n.read()))) && esl_seteq<1,1,1>(and_ln25_fu_241_p2.read(), ap_const_lv1_0))) {
        icmp_ln36_1_reg_377 = icmp_ln36_1_fu_247_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage1_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_2_reg_422.read()))) {
        or_ln36_reg_436 = or_ln36_fu_340_p2.read();
        or_ln37_reg_445 = or_ln37_fu_350_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_reg_385.read()))) {
        or_ln46_reg_399 = or_ln46_fu_286_p2.read();
        or_ln47_reg_408 = or_ln47_fu_296_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        tmp_2_reg_422 = ap_phi_mux_i_0_phi_fu_167_p4.read().range(10, 10);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        tmp_3_reg_385 = ap_phi_mux_i1_0_phi_fu_155_p4.read().range(10, 10);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_reg_385.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_ln46_fu_286_p2.read()))) {
        tmp_V_1_reg_403 = tree_V_q0.read().range(12, 2);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage1_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_2_reg_422.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_ln37_fu_350_p2.read()))) {
        tmp_V_2_reg_449 = tree_V_q1.read().range(23, 13);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_reg_385.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_ln47_fu_296_p2.read()))) {
        tmp_V_3_reg_412 = tree_V_q1.read().range(12, 2);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage1_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_2_reg_422.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_ln36_fu_340_p2.read()))) {
        tmp_V_reg_440 = tree_V_q0.read().range(23, 13);
    }
}

void busqueda_cam::thread_and_ln25_fu_241_p1() {
    and_ln25_fu_241_p1 =  (sc_lv<1>) (fatherSearch.read());
}

void busqueda_cam::thread_and_ln25_fu_241_p2() {
    and_ln25_fu_241_p2 = (icmp_ln25_fu_235_p2.read() & and_ln25_fu_241_p1.read());
}

void busqueda_cam::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void busqueda_cam::thread_ap_CS_fsm_pp0_stage1() {
    ap_CS_fsm_pp0_stage1 = ap_CS_fsm.read()[2];
}

void busqueda_cam::thread_ap_CS_fsm_pp1_stage0() {
    ap_CS_fsm_pp1_stage0 = ap_CS_fsm.read()[4];
}

void busqueda_cam::thread_ap_CS_fsm_pp1_stage1() {
    ap_CS_fsm_pp1_stage1 = ap_CS_fsm.read()[5];
}

void busqueda_cam::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void busqueda_cam::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[3];
}

void busqueda_cam::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void busqueda_cam::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_ln46_reg_399.read()) && esl_seteq<1,1,1>(ap_const_logic_0, result_V_V_full_n.read()));
}

void busqueda_cam::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_ln46_reg_399.read()) && esl_seteq<1,1,1>(ap_const_logic_0, result_V_V_full_n.read()));
}

void busqueda_cam::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_ln46_reg_399.read()) && esl_seteq<1,1,1>(ap_const_logic_0, result_V_V_full_n.read()));
}

void busqueda_cam::thread_ap_block_pp0_stage1() {
    ap_block_pp0_stage1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void busqueda_cam::thread_ap_block_pp0_stage1_01001() {
    ap_block_pp0_stage1_01001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_ln47_reg_408.read()) && esl_seteq<1,1,1>(ap_const_logic_0, result_V_V_full_n.read()));
}

void busqueda_cam::thread_ap_block_pp0_stage1_11001() {
    ap_block_pp0_stage1_11001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_ln47_reg_408.read()) && esl_seteq<1,1,1>(ap_const_logic_0, result_V_V_full_n.read()));
}

void busqueda_cam::thread_ap_block_pp0_stage1_subdone() {
    ap_block_pp0_stage1_subdone = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_ln47_reg_408.read()) && esl_seteq<1,1,1>(ap_const_logic_0, result_V_V_full_n.read()));
}

void busqueda_cam::thread_ap_block_pp1_stage0() {
    ap_block_pp1_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void busqueda_cam::thread_ap_block_pp1_stage0_01001() {
    ap_block_pp1_stage0_01001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && esl_seteq<1,1,1>(or_ln36_reg_436.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, result_V_V_full_n.read()));
}

void busqueda_cam::thread_ap_block_pp1_stage0_11001() {
    ap_block_pp1_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && esl_seteq<1,1,1>(or_ln36_reg_436.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, result_V_V_full_n.read()));
}

void busqueda_cam::thread_ap_block_pp1_stage0_subdone() {
    ap_block_pp1_stage0_subdone = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && esl_seteq<1,1,1>(or_ln36_reg_436.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, result_V_V_full_n.read()));
}

void busqueda_cam::thread_ap_block_pp1_stage1() {
    ap_block_pp1_stage1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void busqueda_cam::thread_ap_block_pp1_stage1_01001() {
    ap_block_pp1_stage1_01001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_ln37_reg_445.read()) && esl_seteq<1,1,1>(ap_const_logic_0, result_V_V_full_n.read()));
}

void busqueda_cam::thread_ap_block_pp1_stage1_11001() {
    ap_block_pp1_stage1_11001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_ln37_reg_445.read()) && esl_seteq<1,1,1>(ap_const_logic_0, result_V_V_full_n.read()));
}

void busqueda_cam::thread_ap_block_pp1_stage1_subdone() {
    ap_block_pp1_stage1_subdone = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_ln37_reg_445.read()) && esl_seteq<1,1,1>(ap_const_logic_0, result_V_V_full_n.read()));
}

void busqueda_cam::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || (esl_seteq<1,1,1>(and_ln25_fu_241_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, result_V_V_full_n.read())));
}

void busqueda_cam::thread_ap_block_state10_pp1_stage1_iter1() {
    ap_block_state10_pp1_stage1_iter1 = (esl_seteq<1,1,1>(ap_const_lv1_0, or_ln37_reg_445.read()) && esl_seteq<1,1,1>(ap_const_logic_0, result_V_V_full_n.read()));
}

void busqueda_cam::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void busqueda_cam::thread_ap_block_state3_pp0_stage1_iter0() {
    ap_block_state3_pp0_stage1_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void busqueda_cam::thread_ap_block_state4_pp0_stage0_iter1() {
    ap_block_state4_pp0_stage0_iter1 = (esl_seteq<1,1,1>(ap_const_lv1_0, or_ln46_reg_399.read()) && esl_seteq<1,1,1>(ap_const_logic_0, result_V_V_full_n.read()));
}

void busqueda_cam::thread_ap_block_state5_pp0_stage1_iter1() {
    ap_block_state5_pp0_stage1_iter1 = (esl_seteq<1,1,1>(ap_const_lv1_0, or_ln47_reg_408.read()) && esl_seteq<1,1,1>(ap_const_logic_0, result_V_V_full_n.read()));
}

void busqueda_cam::thread_ap_block_state6() {
    ap_block_state6 = (esl_seteq<1,1,1>(ap_const_lv1_0, and_ln25_reg_373.read()) && esl_seteq<1,1,1>(ap_const_logic_0, result_V_V_full_n.read()));
}

void busqueda_cam::thread_ap_block_state7_pp1_stage0_iter0() {
    ap_block_state7_pp1_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void busqueda_cam::thread_ap_block_state8_pp1_stage1_iter0() {
    ap_block_state8_pp1_stage1_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void busqueda_cam::thread_ap_block_state9_pp1_stage0_iter1() {
    ap_block_state9_pp1_stage0_iter1 = (esl_seteq<1,1,1>(or_ln36_reg_436.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, result_V_V_full_n.read()));
}

void busqueda_cam::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(ap_const_lv1_1, tmp_3_fu_253_p3.read())) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void busqueda_cam::thread_ap_condition_pp1_exit_iter0_state7() {
    if (esl_seteq<1,1,1>(ap_const_lv1_1, tmp_2_fu_307_p3.read())) {
        ap_condition_pp1_exit_iter0_state7 = ap_const_logic_1;
    } else {
        ap_condition_pp1_exit_iter0_state7 = ap_const_logic_0;
    }
}

void busqueda_cam::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
          !(esl_seteq<1,1,1>(ap_const_lv1_0, and_ln25_reg_373.read()) && esl_seteq<1,1,1>(ap_const_logic_0, result_V_V_full_n.read()))))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void busqueda_cam::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void busqueda_cam::thread_ap_enable_pp1() {
    ap_enable_pp1 = (ap_idle_pp1.read() ^ ap_const_logic_1);
}

void busqueda_cam::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void busqueda_cam::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void busqueda_cam::thread_ap_idle_pp1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter1.read()))) {
        ap_idle_pp1 = ap_const_logic_1;
    } else {
        ap_idle_pp1 = ap_const_logic_0;
    }
}

void busqueda_cam::thread_ap_phi_mux_i1_0_phi_fu_155_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_reg_385.read()))) {
        ap_phi_mux_i1_0_phi_fu_155_p4 = i_1_reg_417.read();
    } else {
        ap_phi_mux_i1_0_phi_fu_155_p4 = i1_0_reg_151.read();
    }
}

void busqueda_cam::thread_ap_phi_mux_i_0_phi_fu_167_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_2_reg_422.read()))) {
        ap_phi_mux_i_0_phi_fu_167_p4 = i_reg_454.read();
    } else {
        ap_phi_mux_i_0_phi_fu_167_p4 = i_0_reg_163.read();
    }
}

void busqueda_cam::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         !(esl_seteq<1,1,1>(ap_const_lv1_0, and_ln25_reg_373.read()) && esl_seteq<1,1,1>(ap_const_logic_0, result_V_V_full_n.read())))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void busqueda_cam::thread_compare_node_max_V_fu_225_p4() {
    compare_node_max_V_fu_225_p4 = tree_V_q1.read().range(12, 2);
}

void busqueda_cam::thread_compare_node_min_V_fu_205_p4() {
    compare_node_min_V_fu_205_p4 = tree_V_q0.read().range(12, 2);
}

void busqueda_cam::thread_fatherSearch_read_read_fu_84_p2() {
    fatherSearch_read_read_fu_84_p2 =  (sc_lv<1>) (fatherSearch.read());
}

void busqueda_cam::thread_grp_fu_175_p4() {
    grp_fu_175_p4 = tree_V_q0.read().range(23, 13);
}

void busqueda_cam::thread_grp_fu_185_p4() {
    grp_fu_185_p4 = tree_V_q1.read().range(23, 13);
}

void busqueda_cam::thread_i_1_fu_301_p2() {
    i_1_fu_301_p2 = (!i1_0_reg_151.read().is_01() || !ap_const_lv11_2.is_01())? sc_lv<11>(): (sc_biguint<11>(i1_0_reg_151.read()) + sc_biguint<11>(ap_const_lv11_2));
}

void busqueda_cam::thread_i_fu_355_p2() {
    i_fu_355_p2 = (!i_0_reg_163.read().is_01() || !ap_const_lv11_2.is_01())? sc_lv<11>(): (sc_biguint<11>(i_0_reg_163.read()) + sc_biguint<11>(ap_const_lv11_2));
}

void busqueda_cam::thread_icmp_ln25_fu_235_p2() {
    icmp_ln25_fu_235_p2 = (!nodo_V.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<1>(): sc_lv<1>(nodo_V.read() == ap_const_lv11_1);
}

void busqueda_cam::thread_icmp_ln36_1_fu_247_p2() {
    icmp_ln36_1_fu_247_p2 = (!relationship_V.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(relationship_V.read() != ap_const_lv2_0);
}

void busqueda_cam::thread_icmp_ln36_fu_335_p2() {
    icmp_ln36_fu_335_p2 = (!compare_node_min_V_fu_205_p4.read().is_01() || !nodo_V.read().is_01())? sc_lv<1>(): sc_lv<1>(compare_node_min_V_fu_205_p4.read() != nodo_V.read());
}

void busqueda_cam::thread_icmp_ln37_fu_345_p2() {
    icmp_ln37_fu_345_p2 = (!compare_node_max_V_fu_225_p4.read().is_01() || !nodo_V.read().is_01())? sc_lv<1>(): sc_lv<1>(compare_node_max_V_fu_225_p4.read() != nodo_V.read());
}

void busqueda_cam::thread_icmp_ln46_fu_281_p2() {
    icmp_ln46_fu_281_p2 = (!grp_fu_175_p4.read().is_01() || !nodo_V.read().is_01())? sc_lv<1>(): sc_lv<1>(grp_fu_175_p4.read() != nodo_V.read());
}

void busqueda_cam::thread_icmp_ln47_fu_291_p2() {
    icmp_ln47_fu_291_p2 = (!grp_fu_185_p4.read().is_01() || !nodo_V.read().is_01())? sc_lv<1>(): sc_lv<1>(grp_fu_185_p4.read() != nodo_V.read());
}

void busqueda_cam::thread_or_ln33_fu_324_p2() {
    or_ln33_fu_324_p2 = (trunc_ln30_fu_315_p1.read() | ap_const_lv10_1);
}

void busqueda_cam::thread_or_ln36_fu_340_p2() {
    or_ln36_fu_340_p2 = (icmp_ln36_fu_335_p2.read() | icmp_ln36_1_reg_377.read());
}

void busqueda_cam::thread_or_ln37_fu_350_p2() {
    or_ln37_fu_350_p2 = (icmp_ln37_fu_345_p2.read() | icmp_ln36_1_reg_377.read());
}

void busqueda_cam::thread_or_ln43_fu_270_p2() {
    or_ln43_fu_270_p2 = (trunc_ln40_fu_261_p1.read() | ap_const_lv10_1);
}

void busqueda_cam::thread_or_ln46_fu_286_p2() {
    or_ln46_fu_286_p2 = (icmp_ln46_fu_281_p2.read() | icmp_ln36_1_reg_377.read());
}

void busqueda_cam::thread_or_ln47_fu_296_p2() {
    or_ln47_fu_296_p2 = (icmp_ln47_fu_291_p2.read() | icmp_ln36_1_reg_377.read());
}

void busqueda_cam::thread_result_V_V_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(and_ln25_fu_241_p2.read(), ap_const_lv1_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(or_ln36_reg_436.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage1.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_ln37_reg_445.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_ln46_reg_399.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_ln47_reg_408.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, and_ln25_reg_373.read())))) {
        result_V_V_blk_n = result_V_V_full_n.read();
    } else {
        result_V_V_blk_n = ap_const_logic_1;
    }
}

void busqueda_cam::thread_result_V_V_din() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, or_ln37_reg_445.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage1_01001.read(), ap_const_boolean_0))) {
        result_V_V_din = tmp_V_2_reg_449.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
                esl_seteq<1,1,1>(or_ln36_reg_436.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_block_pp1_stage0_01001.read(), ap_const_boolean_0))) {
        result_V_V_din = tmp_V_reg_440.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, or_ln47_reg_408.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage1_01001.read(), ap_const_boolean_0))) {
        result_V_V_din = tmp_V_3_reg_412.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, or_ln46_reg_399.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0_01001.read(), ap_const_boolean_0))) {
        result_V_V_din = tmp_V_1_reg_403.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                 esl_seteq<1,1,1>(and_ln25_fu_241_p2.read(), ap_const_lv1_1) && 
                 !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || (esl_seteq<1,1,1>(and_ln25_fu_241_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, result_V_V_full_n.read())))) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, and_ln25_reg_373.read()) && 
                 !(esl_seteq<1,1,1>(ap_const_lv1_0, and_ln25_reg_373.read()) && esl_seteq<1,1,1>(ap_const_logic_0, result_V_V_full_n.read()))))) {
        result_V_V_din = ap_const_lv11_0;
    } else {
        result_V_V_din = "XXXXXXXXXXX";
    }
}

void busqueda_cam::thread_result_V_V_write() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(and_ln25_fu_241_p2.read(), ap_const_lv1_1) && 
          !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || (esl_seteq<1,1,1>(and_ln25_fu_241_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, result_V_V_full_n.read())))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, and_ln25_reg_373.read()) && 
          !(esl_seteq<1,1,1>(ap_const_lv1_0, and_ln25_reg_373.read()) && esl_seteq<1,1,1>(ap_const_logic_0, result_V_V_full_n.read()))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_ln46_reg_399.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_ln47_reg_408.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
          esl_seteq<1,1,1>(or_ln36_reg_436.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage1.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_ln37_reg_445.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage1_11001.read(), ap_const_boolean_0)))) {
        result_V_V_write = ap_const_logic_1;
    } else {
        result_V_V_write = ap_const_logic_0;
    }
}

void busqueda_cam::thread_tmp_2_fu_307_p3() {
    tmp_2_fu_307_p3 = ap_phi_mux_i_0_phi_fu_167_p4.read().range(10, 10);
}

void busqueda_cam::thread_tmp_3_fu_253_p3() {
    tmp_3_fu_253_p3 = ap_phi_mux_i1_0_phi_fu_155_p4.read().range(10, 10);
}

void busqueda_cam::thread_tree_V_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()))) {
        tree_V_address0 =  (sc_lv<10>) (zext_ln32_fu_319_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        tree_V_address0 =  (sc_lv<10>) (zext_ln42_fu_265_p1.read());
    } else {
        tree_V_address0 =  (sc_lv<10>) ("XXXXXXXXXX");
    }
}

void busqueda_cam::thread_tree_V_address1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()))) {
        tree_V_address1 =  (sc_lv<10>) (zext_ln33_fu_330_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        tree_V_address1 =  (sc_lv<10>) (zext_ln43_fu_276_p1.read());
    } else {
        tree_V_address1 =  (sc_lv<10>) ("XXXXXXXXXX");
    }
}

void busqueda_cam::thread_tree_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read())))) {
        tree_V_ce0 = ap_const_logic_1;
    } else {
        tree_V_ce0 = ap_const_logic_0;
    }
}

void busqueda_cam::thread_tree_V_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read())))) {
        tree_V_ce1 = ap_const_logic_1;
    } else {
        tree_V_ce1 = ap_const_logic_0;
    }
}

void busqueda_cam::thread_trunc_ln30_fu_315_p1() {
    trunc_ln30_fu_315_p1 = ap_phi_mux_i_0_phi_fu_167_p4.read().range(10-1, 0);
}

void busqueda_cam::thread_trunc_ln40_fu_261_p1() {
    trunc_ln40_fu_261_p1 = ap_phi_mux_i1_0_phi_fu_155_p4.read().range(10-1, 0);
}

void busqueda_cam::thread_zext_ln32_fu_319_p1() {
    zext_ln32_fu_319_p1 = esl_zext<64,11>(ap_phi_mux_i_0_phi_fu_167_p4.read());
}

void busqueda_cam::thread_zext_ln33_fu_330_p1() {
    zext_ln33_fu_330_p1 = esl_zext<64,10>(or_ln33_fu_324_p2.read());
}

void busqueda_cam::thread_zext_ln42_fu_265_p1() {
    zext_ln42_fu_265_p1 = esl_zext<64,11>(ap_phi_mux_i1_0_phi_fu_155_p4.read());
}

void busqueda_cam::thread_zext_ln43_fu_276_p1() {
    zext_ln43_fu_276_p1 = esl_zext<64,10>(or_ln43_fu_270_p2.read());
}

void busqueda_cam::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(and_ln25_fu_241_p2.read(), ap_const_lv1_1) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || (esl_seteq<1,1,1>(and_ln25_fu_241_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, result_V_V_full_n.read()))))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || (esl_seteq<1,1,1>(and_ln25_fu_241_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, result_V_V_full_n.read()))) && esl_seteq<1,1,1>(and_ln25_fu_241_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_1, fatherSearch_read_read_fu_84_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || (esl_seteq<1,1,1>(and_ln25_fu_241_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, result_V_V_full_n.read()))) && esl_seteq<1,1,1>(and_ln25_fu_241_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_0, fatherSearch_read_read_fu_84_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_3_fu_253_p3.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_3_fu_253_p3.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && !(esl_seteq<1,1,1>(ap_const_lv1_0, and_ln25_reg_373.read()) && esl_seteq<1,1,1>(ap_const_logic_0, result_V_V_full_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_2_fu_307_p3.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp1_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_2_fu_307_p3.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp1_iter1.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_block_pp1_stage1_subdone.read(), ap_const_boolean_0) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage1_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp1_iter0.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage1_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp1_iter0.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp1_stage1;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<6>) ("XXXXXX");
            break;
    }
}

}

