// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _top_function_HH_
#define _top_function_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "busqueda_cam.h"

namespace ap_rtl {

struct top_function : public sc_module {
    // Port declarations 22
    sc_out< sc_lv<10> > tree_V_address0;
    sc_out< sc_logic > tree_V_ce0;
    sc_out< sc_lv<24> > tree_V_d0;
    sc_in< sc_lv<24> > tree_V_q0;
    sc_out< sc_logic > tree_V_we0;
    sc_out< sc_lv<10> > tree_V_address1;
    sc_out< sc_logic > tree_V_ce1;
    sc_out< sc_lv<24> > tree_V_d1;
    sc_in< sc_lv<24> > tree_V_q1;
    sc_out< sc_logic > tree_V_we1;
    sc_in< sc_lv<11> > nodo_V;
    sc_in< sc_lv<2> > relationship_V;
    sc_in< sc_logic > fatherSearch;
    sc_out< sc_lv<11> > result_V_V_din;
    sc_in< sc_logic > result_V_V_full_n;
    sc_out< sc_logic > result_V_V_write;
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_logic > ap_idle;


    // Module declarations
    top_function(sc_module_name name);
    SC_HAS_PROCESS(top_function);

    ~top_function();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    busqueda_cam* busqueda_cam_U0;
    sc_signal< sc_logic > busqueda_cam_U0_ap_start;
    sc_signal< sc_logic > busqueda_cam_U0_ap_done;
    sc_signal< sc_logic > busqueda_cam_U0_ap_continue;
    sc_signal< sc_logic > busqueda_cam_U0_ap_idle;
    sc_signal< sc_logic > busqueda_cam_U0_ap_ready;
    sc_signal< sc_lv<10> > busqueda_cam_U0_tree_V_address0;
    sc_signal< sc_logic > busqueda_cam_U0_tree_V_ce0;
    sc_signal< sc_lv<11> > busqueda_cam_U0_result_V_V_din;
    sc_signal< sc_logic > busqueda_cam_U0_result_V_V_write;
    sc_signal< sc_logic > ap_sync_continue;
    sc_signal< sc_logic > ap_sync_done;
    sc_signal< sc_logic > ap_sync_ready;
    sc_signal< sc_logic > busqueda_cam_U0_start_full_n;
    sc_signal< sc_logic > busqueda_cam_U0_start_write;
    static const sc_lv<10> ap_const_lv10_0;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<24> ap_const_lv24_0;
    static const sc_lv<11> ap_const_lv11_0;
    static const sc_logic ap_const_logic_1;
    // Thread declarations
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sync_continue();
    void thread_ap_sync_done();
    void thread_ap_sync_ready();
    void thread_busqueda_cam_U0_ap_continue();
    void thread_busqueda_cam_U0_ap_start();
    void thread_busqueda_cam_U0_start_full_n();
    void thread_busqueda_cam_U0_start_write();
    void thread_result_V_V_din();
    void thread_result_V_V_write();
    void thread_tree_V_address0();
    void thread_tree_V_address1();
    void thread_tree_V_ce0();
    void thread_tree_V_ce1();
    void thread_tree_V_d0();
    void thread_tree_V_d1();
    void thread_tree_V_we0();
    void thread_tree_V_we1();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
