// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "top_function.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_lv<9> top_function::ap_const_lv9_0 = "000000000";
const sc_logic top_function::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<24> top_function::ap_const_lv24_0 = "000000000000000000000000";
const sc_lv<10> top_function::ap_const_lv10_0 = "0000000000";
const sc_lv<11> top_function::ap_const_lv11_0 = "00000000000";
const sc_logic top_function::ap_const_logic_1 = sc_dt::Log_1;
const sc_lv<2> top_function::ap_const_lv2_0 = "00";
const sc_lv<2> top_function::ap_const_lv2_1 = "1";
const bool top_function::ap_const_boolean_1 = true;

top_function::top_function(sc_module_name name) : sc_module(name), mVcdFile(0) {
    top_function_entry3_U0 = new top_function_entry3("top_function_entry3_U0");
    top_function_entry3_U0->ap_clk(ap_clk);
    top_function_entry3_U0->ap_rst(ap_rst);
    top_function_entry3_U0->ap_start(top_function_entry3_U0_ap_start);
    top_function_entry3_U0->start_full_n(start_for_top_function_entry43_U0_full_n);
    top_function_entry3_U0->ap_done(top_function_entry3_U0_ap_done);
    top_function_entry3_U0->ap_continue(top_function_entry3_U0_ap_continue);
    top_function_entry3_U0->ap_idle(top_function_entry3_U0_ap_idle);
    top_function_entry3_U0->ap_ready(top_function_entry3_U0_ap_ready);
    top_function_entry3_U0->start_out(top_function_entry3_U0_start_out);
    top_function_entry3_U0->start_write(top_function_entry3_U0_start_write);
    top_function_entry3_U0->nodo_V(nodo_V);
    top_function_entry3_U0->relationship_V(relationship_V);
    top_function_entry3_U0->fatherSearch(top_function_entry3_U0_fatherSearch);
    top_function_entry3_U0->nodo_V_out_din(top_function_entry3_U0_nodo_V_out_din);
    top_function_entry3_U0->nodo_V_out_full_n(nodo_V_c1_full_n);
    top_function_entry3_U0->nodo_V_out_write(top_function_entry3_U0_nodo_V_out_write);
    top_function_entry3_U0->relationship_V_out_din(top_function_entry3_U0_relationship_V_out_din);
    top_function_entry3_U0->relationship_V_out_full_n(relationship_V_c2_full_n);
    top_function_entry3_U0->relationship_V_out_write(top_function_entry3_U0_relationship_V_out_write);
    top_function_entry3_U0->fatherSearch_out_din(top_function_entry3_U0_fatherSearch_out_din);
    top_function_entry3_U0->fatherSearch_out_full_n(fatherSearch_c3_full_n);
    top_function_entry3_U0->fatherSearch_out_write(top_function_entry3_U0_fatherSearch_out_write);
    top_function_entry43_U0 = new top_function_entry43("top_function_entry43_U0");
    top_function_entry43_U0->ap_clk(ap_clk);
    top_function_entry43_U0->ap_rst(ap_rst);
    top_function_entry43_U0->ap_start(top_function_entry43_U0_ap_start);
    top_function_entry43_U0->ap_done(top_function_entry43_U0_ap_done);
    top_function_entry43_U0->ap_continue(top_function_entry43_U0_ap_continue);
    top_function_entry43_U0->ap_idle(top_function_entry43_U0_ap_idle);
    top_function_entry43_U0->ap_ready(top_function_entry43_U0_ap_ready);
    top_function_entry43_U0->nodo_V_dout(nodo_V_c1_dout);
    top_function_entry43_U0->nodo_V_empty_n(nodo_V_c1_empty_n);
    top_function_entry43_U0->nodo_V_read(top_function_entry43_U0_nodo_V_read);
    top_function_entry43_U0->relationship_V_dout(relationship_V_c2_dout);
    top_function_entry43_U0->relationship_V_empty_n(relationship_V_c2_empty_n);
    top_function_entry43_U0->relationship_V_read(top_function_entry43_U0_relationship_V_read);
    top_function_entry43_U0->fatherSearch_dout(fatherSearch_c3_dout);
    top_function_entry43_U0->fatherSearch_empty_n(fatherSearch_c3_empty_n);
    top_function_entry43_U0->fatherSearch_read(top_function_entry43_U0_fatherSearch_read);
    top_function_entry43_U0->nodo_V_out_din(top_function_entry43_U0_nodo_V_out_din);
    top_function_entry43_U0->nodo_V_out_full_n(nodo_V_c_full_n);
    top_function_entry43_U0->nodo_V_out_write(top_function_entry43_U0_nodo_V_out_write);
    top_function_entry43_U0->nodo_V_out1_din(top_function_entry43_U0_nodo_V_out1_din);
    top_function_entry43_U0->nodo_V_out1_full_n(nodo_V_c7_full_n);
    top_function_entry43_U0->nodo_V_out1_write(top_function_entry43_U0_nodo_V_out1_write);
    top_function_entry43_U0->relationship_V_out_din(top_function_entry43_U0_relationship_V_out_din);
    top_function_entry43_U0->relationship_V_out_full_n(relationship_V_c_full_n);
    top_function_entry43_U0->relationship_V_out_write(top_function_entry43_U0_relationship_V_out_write);
    top_function_entry43_U0->relationship_V_out2_din(top_function_entry43_U0_relationship_V_out2_din);
    top_function_entry43_U0->relationship_V_out2_full_n(relationship_V_c8_full_n);
    top_function_entry43_U0->relationship_V_out2_write(top_function_entry43_U0_relationship_V_out2_write);
    top_function_entry43_U0->fatherSearch_out_din(top_function_entry43_U0_fatherSearch_out_din);
    top_function_entry43_U0->fatherSearch_out_full_n(fatherSearch_c_full_n);
    top_function_entry43_U0->fatherSearch_out_write(top_function_entry43_U0_fatherSearch_out_write);
    top_function_entry43_U0->fatherSearch_out3_din(top_function_entry43_U0_fatherSearch_out3_din);
    top_function_entry43_U0->fatherSearch_out3_full_n(fatherSearch_c9_full_n);
    top_function_entry43_U0->fatherSearch_out3_write(top_function_entry43_U0_fatherSearch_out3_write);
    busqueda_cam_1_U0 = new busqueda_cam_1("busqueda_cam_1_U0");
    busqueda_cam_1_U0->ap_clk(ap_clk);
    busqueda_cam_1_U0->ap_rst(ap_rst);
    busqueda_cam_1_U0->ap_start(busqueda_cam_1_U0_ap_start);
    busqueda_cam_1_U0->start_full_n(start_for_combinar_U0_full_n);
    busqueda_cam_1_U0->ap_done(busqueda_cam_1_U0_ap_done);
    busqueda_cam_1_U0->ap_continue(busqueda_cam_1_U0_ap_continue);
    busqueda_cam_1_U0->ap_idle(busqueda_cam_1_U0_ap_idle);
    busqueda_cam_1_U0->ap_ready(busqueda_cam_1_U0_ap_ready);
    busqueda_cam_1_U0->start_out(busqueda_cam_1_U0_start_out);
    busqueda_cam_1_U0->start_write(busqueda_cam_1_U0_start_write);
    busqueda_cam_1_U0->tree_V_address0(busqueda_cam_1_U0_tree_V_address0);
    busqueda_cam_1_U0->tree_V_ce0(busqueda_cam_1_U0_tree_V_ce0);
    busqueda_cam_1_U0->tree_V_q0(tree1_V_q0);
    busqueda_cam_1_U0->tree_V_address1(busqueda_cam_1_U0_tree_V_address1);
    busqueda_cam_1_U0->tree_V_ce1(busqueda_cam_1_U0_tree_V_ce1);
    busqueda_cam_1_U0->tree_V_q1(tree1_V_q1);
    busqueda_cam_1_U0->nodo_V_dout(nodo_V_c_dout);
    busqueda_cam_1_U0->nodo_V_empty_n(nodo_V_c_empty_n);
    busqueda_cam_1_U0->nodo_V_read(busqueda_cam_1_U0_nodo_V_read);
    busqueda_cam_1_U0->relationship_V_dout(relationship_V_c_dout);
    busqueda_cam_1_U0->relationship_V_empty_n(relationship_V_c_empty_n);
    busqueda_cam_1_U0->relationship_V_read(busqueda_cam_1_U0_relationship_V_read);
    busqueda_cam_1_U0->fatherSearch_dout(fatherSearch_c_dout);
    busqueda_cam_1_U0->fatherSearch_empty_n(fatherSearch_c_empty_n);
    busqueda_cam_1_U0->fatherSearch_read(busqueda_cam_1_U0_fatherSearch_read);
    busqueda_cam_1_U0->in1_V_V_din(busqueda_cam_1_U0_in1_V_V_din);
    busqueda_cam_1_U0->in1_V_V_full_n(in1_V_V_full_n);
    busqueda_cam_1_U0->in1_V_V_write(busqueda_cam_1_U0_in1_V_V_write);
    busqueda_cam_1_U0->in1b_V_V_din(busqueda_cam_1_U0_in1b_V_V_din);
    busqueda_cam_1_U0->in1b_V_V_full_n(in1b_V_V_full_n);
    busqueda_cam_1_U0->in1b_V_V_write(busqueda_cam_1_U0_in1b_V_V_write);
    busqueda_cam_U0 = new busqueda_cam("busqueda_cam_U0");
    busqueda_cam_U0->ap_clk(ap_clk);
    busqueda_cam_U0->ap_rst(ap_rst);
    busqueda_cam_U0->ap_start(busqueda_cam_U0_ap_start);
    busqueda_cam_U0->ap_done(busqueda_cam_U0_ap_done);
    busqueda_cam_U0->ap_continue(busqueda_cam_U0_ap_continue);
    busqueda_cam_U0->ap_idle(busqueda_cam_U0_ap_idle);
    busqueda_cam_U0->ap_ready(busqueda_cam_U0_ap_ready);
    busqueda_cam_U0->tree_V_address0(busqueda_cam_U0_tree_V_address0);
    busqueda_cam_U0->tree_V_ce0(busqueda_cam_U0_tree_V_ce0);
    busqueda_cam_U0->tree_V_q0(tree2_V_q0);
    busqueda_cam_U0->tree_V_address1(busqueda_cam_U0_tree_V_address1);
    busqueda_cam_U0->tree_V_ce1(busqueda_cam_U0_tree_V_ce1);
    busqueda_cam_U0->tree_V_q1(tree2_V_q1);
    busqueda_cam_U0->nodo_V_dout(nodo_V_c7_dout);
    busqueda_cam_U0->nodo_V_empty_n(nodo_V_c7_empty_n);
    busqueda_cam_U0->nodo_V_read(busqueda_cam_U0_nodo_V_read);
    busqueda_cam_U0->relationship_V_dout(relationship_V_c8_dout);
    busqueda_cam_U0->relationship_V_empty_n(relationship_V_c8_empty_n);
    busqueda_cam_U0->relationship_V_read(busqueda_cam_U0_relationship_V_read);
    busqueda_cam_U0->fatherSearch_dout(fatherSearch_c9_dout);
    busqueda_cam_U0->fatherSearch_empty_n(fatherSearch_c9_empty_n);
    busqueda_cam_U0->fatherSearch_read(busqueda_cam_U0_fatherSearch_read);
    busqueda_cam_U0->in2_V_V_din(busqueda_cam_U0_in2_V_V_din);
    busqueda_cam_U0->in2_V_V_full_n(in2_V_V_full_n);
    busqueda_cam_U0->in2_V_V_write(busqueda_cam_U0_in2_V_V_write);
    busqueda_cam_U0->in2b_V_V_din(busqueda_cam_U0_in2b_V_V_din);
    busqueda_cam_U0->in2b_V_V_full_n(in2b_V_V_full_n);
    busqueda_cam_U0->in2b_V_V_write(busqueda_cam_U0_in2b_V_V_write);
    combinar_U0 = new combinar("combinar_U0");
    combinar_U0->ap_clk(ap_clk);
    combinar_U0->ap_rst(ap_rst);
    combinar_U0->ap_start(combinar_U0_ap_start);
    combinar_U0->ap_done(combinar_U0_ap_done);
    combinar_U0->ap_continue(combinar_U0_ap_continue);
    combinar_U0->ap_idle(combinar_U0_ap_idle);
    combinar_U0->ap_ready(combinar_U0_ap_ready);
    combinar_U0->result_V_V_din(combinar_U0_result_V_V_din);
    combinar_U0->result_V_V_full_n(result_V_V_full_n);
    combinar_U0->result_V_V_write(combinar_U0_result_V_V_write);
    combinar_U0->in1_V_V_dout(in1_V_V_dout);
    combinar_U0->in1_V_V_empty_n(in1_V_V_empty_n);
    combinar_U0->in1_V_V_read(combinar_U0_in1_V_V_read);
    combinar_U0->in2_V_V_dout(in2_V_V_dout);
    combinar_U0->in2_V_V_empty_n(in2_V_V_empty_n);
    combinar_U0->in2_V_V_read(combinar_U0_in2_V_V_read);
    combinar_U0->in1b_V_V_dout(in1b_V_V_dout);
    combinar_U0->in1b_V_V_empty_n(in1b_V_V_empty_n);
    combinar_U0->in1b_V_V_read(combinar_U0_in1b_V_V_read);
    combinar_U0->in2b_V_V_dout(in2b_V_V_dout);
    combinar_U0->in2b_V_V_empty_n(in2b_V_V_empty_n);
    combinar_U0->in2b_V_V_read(combinar_U0_in2b_V_V_read);
    nodo_V_c1_U = new fifo_w11_d2_A("nodo_V_c1_U");
    nodo_V_c1_U->clk(ap_clk);
    nodo_V_c1_U->reset(ap_rst);
    nodo_V_c1_U->if_read_ce(ap_var_for_const0);
    nodo_V_c1_U->if_write_ce(ap_var_for_const0);
    nodo_V_c1_U->if_din(top_function_entry3_U0_nodo_V_out_din);
    nodo_V_c1_U->if_full_n(nodo_V_c1_full_n);
    nodo_V_c1_U->if_write(top_function_entry3_U0_nodo_V_out_write);
    nodo_V_c1_U->if_dout(nodo_V_c1_dout);
    nodo_V_c1_U->if_empty_n(nodo_V_c1_empty_n);
    nodo_V_c1_U->if_read(top_function_entry43_U0_nodo_V_read);
    relationship_V_c2_U = new fifo_w2_d2_A("relationship_V_c2_U");
    relationship_V_c2_U->clk(ap_clk);
    relationship_V_c2_U->reset(ap_rst);
    relationship_V_c2_U->if_read_ce(ap_var_for_const0);
    relationship_V_c2_U->if_write_ce(ap_var_for_const0);
    relationship_V_c2_U->if_din(top_function_entry3_U0_relationship_V_out_din);
    relationship_V_c2_U->if_full_n(relationship_V_c2_full_n);
    relationship_V_c2_U->if_write(top_function_entry3_U0_relationship_V_out_write);
    relationship_V_c2_U->if_dout(relationship_V_c2_dout);
    relationship_V_c2_U->if_empty_n(relationship_V_c2_empty_n);
    relationship_V_c2_U->if_read(top_function_entry43_U0_relationship_V_read);
    fatherSearch_c3_U = new fifo_w1_d2_A("fatherSearch_c3_U");
    fatherSearch_c3_U->clk(ap_clk);
    fatherSearch_c3_U->reset(ap_rst);
    fatherSearch_c3_U->if_read_ce(ap_var_for_const0);
    fatherSearch_c3_U->if_write_ce(ap_var_for_const0);
    fatherSearch_c3_U->if_din(top_function_entry3_U0_fatherSearch_out_din);
    fatherSearch_c3_U->if_full_n(fatherSearch_c3_full_n);
    fatherSearch_c3_U->if_write(top_function_entry3_U0_fatherSearch_out_write);
    fatherSearch_c3_U->if_dout(fatherSearch_c3_dout);
    fatherSearch_c3_U->if_empty_n(fatherSearch_c3_empty_n);
    fatherSearch_c3_U->if_read(top_function_entry43_U0_fatherSearch_read);
    nodo_V_c_U = new fifo_w11_d2_A("nodo_V_c_U");
    nodo_V_c_U->clk(ap_clk);
    nodo_V_c_U->reset(ap_rst);
    nodo_V_c_U->if_read_ce(ap_var_for_const0);
    nodo_V_c_U->if_write_ce(ap_var_for_const0);
    nodo_V_c_U->if_din(top_function_entry43_U0_nodo_V_out_din);
    nodo_V_c_U->if_full_n(nodo_V_c_full_n);
    nodo_V_c_U->if_write(top_function_entry43_U0_nodo_V_out_write);
    nodo_V_c_U->if_dout(nodo_V_c_dout);
    nodo_V_c_U->if_empty_n(nodo_V_c_empty_n);
    nodo_V_c_U->if_read(busqueda_cam_1_U0_nodo_V_read);
    nodo_V_c7_U = new fifo_w11_d2_A("nodo_V_c7_U");
    nodo_V_c7_U->clk(ap_clk);
    nodo_V_c7_U->reset(ap_rst);
    nodo_V_c7_U->if_read_ce(ap_var_for_const0);
    nodo_V_c7_U->if_write_ce(ap_var_for_const0);
    nodo_V_c7_U->if_din(top_function_entry43_U0_nodo_V_out1_din);
    nodo_V_c7_U->if_full_n(nodo_V_c7_full_n);
    nodo_V_c7_U->if_write(top_function_entry43_U0_nodo_V_out1_write);
    nodo_V_c7_U->if_dout(nodo_V_c7_dout);
    nodo_V_c7_U->if_empty_n(nodo_V_c7_empty_n);
    nodo_V_c7_U->if_read(busqueda_cam_U0_nodo_V_read);
    relationship_V_c_U = new fifo_w2_d2_A("relationship_V_c_U");
    relationship_V_c_U->clk(ap_clk);
    relationship_V_c_U->reset(ap_rst);
    relationship_V_c_U->if_read_ce(ap_var_for_const0);
    relationship_V_c_U->if_write_ce(ap_var_for_const0);
    relationship_V_c_U->if_din(top_function_entry43_U0_relationship_V_out_din);
    relationship_V_c_U->if_full_n(relationship_V_c_full_n);
    relationship_V_c_U->if_write(top_function_entry43_U0_relationship_V_out_write);
    relationship_V_c_U->if_dout(relationship_V_c_dout);
    relationship_V_c_U->if_empty_n(relationship_V_c_empty_n);
    relationship_V_c_U->if_read(busqueda_cam_1_U0_relationship_V_read);
    relationship_V_c8_U = new fifo_w2_d2_A("relationship_V_c8_U");
    relationship_V_c8_U->clk(ap_clk);
    relationship_V_c8_U->reset(ap_rst);
    relationship_V_c8_U->if_read_ce(ap_var_for_const0);
    relationship_V_c8_U->if_write_ce(ap_var_for_const0);
    relationship_V_c8_U->if_din(top_function_entry43_U0_relationship_V_out2_din);
    relationship_V_c8_U->if_full_n(relationship_V_c8_full_n);
    relationship_V_c8_U->if_write(top_function_entry43_U0_relationship_V_out2_write);
    relationship_V_c8_U->if_dout(relationship_V_c8_dout);
    relationship_V_c8_U->if_empty_n(relationship_V_c8_empty_n);
    relationship_V_c8_U->if_read(busqueda_cam_U0_relationship_V_read);
    fatherSearch_c_U = new fifo_w1_d2_A("fatherSearch_c_U");
    fatherSearch_c_U->clk(ap_clk);
    fatherSearch_c_U->reset(ap_rst);
    fatherSearch_c_U->if_read_ce(ap_var_for_const0);
    fatherSearch_c_U->if_write_ce(ap_var_for_const0);
    fatherSearch_c_U->if_din(top_function_entry43_U0_fatherSearch_out_din);
    fatherSearch_c_U->if_full_n(fatherSearch_c_full_n);
    fatherSearch_c_U->if_write(top_function_entry43_U0_fatherSearch_out_write);
    fatherSearch_c_U->if_dout(fatherSearch_c_dout);
    fatherSearch_c_U->if_empty_n(fatherSearch_c_empty_n);
    fatherSearch_c_U->if_read(busqueda_cam_1_U0_fatherSearch_read);
    fatherSearch_c9_U = new fifo_w1_d2_A("fatherSearch_c9_U");
    fatherSearch_c9_U->clk(ap_clk);
    fatherSearch_c9_U->reset(ap_rst);
    fatherSearch_c9_U->if_read_ce(ap_var_for_const0);
    fatherSearch_c9_U->if_write_ce(ap_var_for_const0);
    fatherSearch_c9_U->if_din(top_function_entry43_U0_fatherSearch_out3_din);
    fatherSearch_c9_U->if_full_n(fatherSearch_c9_full_n);
    fatherSearch_c9_U->if_write(top_function_entry43_U0_fatherSearch_out3_write);
    fatherSearch_c9_U->if_dout(fatherSearch_c9_dout);
    fatherSearch_c9_U->if_empty_n(fatherSearch_c9_empty_n);
    fatherSearch_c9_U->if_read(busqueda_cam_U0_fatherSearch_read);
    in1_V_V_U = new fifo_w11_d8_A("in1_V_V_U");
    in1_V_V_U->clk(ap_clk);
    in1_V_V_U->reset(ap_rst);
    in1_V_V_U->if_read_ce(ap_var_for_const0);
    in1_V_V_U->if_write_ce(ap_var_for_const0);
    in1_V_V_U->if_din(busqueda_cam_1_U0_in1_V_V_din);
    in1_V_V_U->if_full_n(in1_V_V_full_n);
    in1_V_V_U->if_write(busqueda_cam_1_U0_in1_V_V_write);
    in1_V_V_U->if_dout(in1_V_V_dout);
    in1_V_V_U->if_empty_n(in1_V_V_empty_n);
    in1_V_V_U->if_read(combinar_U0_in1_V_V_read);
    in1b_V_V_U = new fifo_w11_d8_A("in1b_V_V_U");
    in1b_V_V_U->clk(ap_clk);
    in1b_V_V_U->reset(ap_rst);
    in1b_V_V_U->if_read_ce(ap_var_for_const0);
    in1b_V_V_U->if_write_ce(ap_var_for_const0);
    in1b_V_V_U->if_din(busqueda_cam_1_U0_in1b_V_V_din);
    in1b_V_V_U->if_full_n(in1b_V_V_full_n);
    in1b_V_V_U->if_write(busqueda_cam_1_U0_in1b_V_V_write);
    in1b_V_V_U->if_dout(in1b_V_V_dout);
    in1b_V_V_U->if_empty_n(in1b_V_V_empty_n);
    in1b_V_V_U->if_read(combinar_U0_in1b_V_V_read);
    in2_V_V_U = new fifo_w11_d8_A("in2_V_V_U");
    in2_V_V_U->clk(ap_clk);
    in2_V_V_U->reset(ap_rst);
    in2_V_V_U->if_read_ce(ap_var_for_const0);
    in2_V_V_U->if_write_ce(ap_var_for_const0);
    in2_V_V_U->if_din(busqueda_cam_U0_in2_V_V_din);
    in2_V_V_U->if_full_n(in2_V_V_full_n);
    in2_V_V_U->if_write(busqueda_cam_U0_in2_V_V_write);
    in2_V_V_U->if_dout(in2_V_V_dout);
    in2_V_V_U->if_empty_n(in2_V_V_empty_n);
    in2_V_V_U->if_read(combinar_U0_in2_V_V_read);
    in2b_V_V_U = new fifo_w11_d8_A("in2b_V_V_U");
    in2b_V_V_U->clk(ap_clk);
    in2b_V_V_U->reset(ap_rst);
    in2b_V_V_U->if_read_ce(ap_var_for_const0);
    in2b_V_V_U->if_write_ce(ap_var_for_const0);
    in2b_V_V_U->if_din(busqueda_cam_U0_in2b_V_V_din);
    in2b_V_V_U->if_full_n(in2b_V_V_full_n);
    in2b_V_V_U->if_write(busqueda_cam_U0_in2b_V_V_write);
    in2b_V_V_U->if_dout(in2b_V_V_dout);
    in2b_V_V_U->if_empty_n(in2b_V_V_empty_n);
    in2b_V_V_U->if_read(combinar_U0_in2b_V_V_read);
    start_for_top_funbkb_U = new start_for_top_funbkb("start_for_top_funbkb_U");
    start_for_top_funbkb_U->clk(ap_clk);
    start_for_top_funbkb_U->reset(ap_rst);
    start_for_top_funbkb_U->if_read_ce(ap_var_for_const0);
    start_for_top_funbkb_U->if_write_ce(ap_var_for_const0);
    start_for_top_funbkb_U->if_din(start_for_top_function_entry43_U0_din);
    start_for_top_funbkb_U->if_full_n(start_for_top_function_entry43_U0_full_n);
    start_for_top_funbkb_U->if_write(top_function_entry3_U0_start_write);
    start_for_top_funbkb_U->if_dout(start_for_top_function_entry43_U0_dout);
    start_for_top_funbkb_U->if_empty_n(start_for_top_function_entry43_U0_empty_n);
    start_for_top_funbkb_U->if_read(top_function_entry43_U0_ap_ready);
    start_for_combinacud_U = new start_for_combinacud("start_for_combinacud_U");
    start_for_combinacud_U->clk(ap_clk);
    start_for_combinacud_U->reset(ap_rst);
    start_for_combinacud_U->if_read_ce(ap_var_for_const0);
    start_for_combinacud_U->if_write_ce(ap_var_for_const0);
    start_for_combinacud_U->if_din(start_for_combinar_U0_din);
    start_for_combinacud_U->if_full_n(start_for_combinar_U0_full_n);
    start_for_combinacud_U->if_write(busqueda_cam_1_U0_start_write);
    start_for_combinacud_U->if_dout(start_for_combinar_U0_dout);
    start_for_combinacud_U->if_empty_n(start_for_combinar_U0_empty_n);
    start_for_combinacud_U->if_read(combinar_U0_ap_ready);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( combinar_U0_ap_done );

    SC_METHOD(thread_ap_idle);
    sensitive << ( top_function_entry3_U0_ap_idle );
    sensitive << ( top_function_entry43_U0_ap_idle );
    sensitive << ( busqueda_cam_1_U0_ap_idle );
    sensitive << ( busqueda_cam_U0_ap_idle );
    sensitive << ( combinar_U0_ap_idle );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sync_ready );

    SC_METHOD(thread_ap_sync_busqueda_cam_1_U0_ap_ready);
    sensitive << ( busqueda_cam_1_U0_ap_ready );
    sensitive << ( ap_sync_reg_busqueda_cam_1_U0_ap_ready );

    SC_METHOD(thread_ap_sync_busqueda_cam_U0_ap_ready);
    sensitive << ( busqueda_cam_U0_ap_ready );
    sensitive << ( ap_sync_reg_busqueda_cam_U0_ap_ready );

    SC_METHOD(thread_ap_sync_continue);

    SC_METHOD(thread_ap_sync_done);
    sensitive << ( combinar_U0_ap_done );

    SC_METHOD(thread_ap_sync_ready);
    sensitive << ( ap_sync_top_function_entry3_U0_ap_ready );
    sensitive << ( ap_sync_busqueda_cam_1_U0_ap_ready );
    sensitive << ( ap_sync_busqueda_cam_U0_ap_ready );

    SC_METHOD(thread_ap_sync_top_function_entry3_U0_ap_ready);
    sensitive << ( top_function_entry3_U0_ap_ready );
    sensitive << ( ap_sync_reg_top_function_entry3_U0_ap_ready );

    SC_METHOD(thread_busqueda_cam_1_U0_ap_continue);

    SC_METHOD(thread_busqueda_cam_1_U0_ap_start);
    sensitive << ( ap_start );
    sensitive << ( ap_sync_reg_busqueda_cam_1_U0_ap_ready );

    SC_METHOD(thread_busqueda_cam_U0_ap_continue);

    SC_METHOD(thread_busqueda_cam_U0_ap_start);
    sensitive << ( ap_start );
    sensitive << ( ap_sync_reg_busqueda_cam_U0_ap_ready );

    SC_METHOD(thread_busqueda_cam_U0_start_full_n);

    SC_METHOD(thread_busqueda_cam_U0_start_write);

    SC_METHOD(thread_combinar_U0_ap_continue);

    SC_METHOD(thread_combinar_U0_ap_start);
    sensitive << ( start_for_combinar_U0_empty_n );

    SC_METHOD(thread_combinar_U0_start_full_n);

    SC_METHOD(thread_combinar_U0_start_write);

    SC_METHOD(thread_result_V_V_din);
    sensitive << ( combinar_U0_result_V_V_din );

    SC_METHOD(thread_result_V_V_write);
    sensitive << ( combinar_U0_result_V_V_write );

    SC_METHOD(thread_start_for_combinar_U0_din);

    SC_METHOD(thread_start_for_top_function_entry43_U0_din);

    SC_METHOD(thread_top_function_entry3_U0_ap_continue);

    SC_METHOD(thread_top_function_entry3_U0_ap_start);
    sensitive << ( ap_start );
    sensitive << ( ap_sync_reg_top_function_entry3_U0_ap_ready );

    SC_METHOD(thread_top_function_entry3_U0_fatherSearch);
    sensitive << ( fatherSearch );

    SC_METHOD(thread_top_function_entry43_U0_ap_continue);

    SC_METHOD(thread_top_function_entry43_U0_ap_start);
    sensitive << ( start_for_top_function_entry43_U0_empty_n );

    SC_METHOD(thread_top_function_entry43_U0_start_full_n);

    SC_METHOD(thread_top_function_entry43_U0_start_write);

    SC_METHOD(thread_tree1_V_address0);
    sensitive << ( busqueda_cam_1_U0_tree_V_address0 );

    SC_METHOD(thread_tree1_V_address1);
    sensitive << ( busqueda_cam_1_U0_tree_V_address1 );

    SC_METHOD(thread_tree1_V_ce0);
    sensitive << ( busqueda_cam_1_U0_tree_V_ce0 );

    SC_METHOD(thread_tree1_V_ce1);
    sensitive << ( busqueda_cam_1_U0_tree_V_ce1 );

    SC_METHOD(thread_tree1_V_d0);

    SC_METHOD(thread_tree1_V_d1);

    SC_METHOD(thread_tree1_V_we0);

    SC_METHOD(thread_tree1_V_we1);

    SC_METHOD(thread_tree2_V_address0);
    sensitive << ( busqueda_cam_U0_tree_V_address0 );

    SC_METHOD(thread_tree2_V_address1);
    sensitive << ( busqueda_cam_U0_tree_V_address1 );

    SC_METHOD(thread_tree2_V_ce0);
    sensitive << ( busqueda_cam_U0_tree_V_ce0 );

    SC_METHOD(thread_tree2_V_ce1);
    sensitive << ( busqueda_cam_U0_tree_V_ce1 );

    SC_METHOD(thread_tree2_V_d0);

    SC_METHOD(thread_tree2_V_d1);

    SC_METHOD(thread_tree2_V_we0);

    SC_METHOD(thread_tree2_V_we1);

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_sync_reg_top_function_entry3_U0_ap_ready = SC_LOGIC_0;
    top_function_entry3_U0_ap_ready_count = "00";
    ap_sync_reg_busqueda_cam_1_U0_ap_ready = SC_LOGIC_0;
    busqueda_cam_1_U0_ap_ready_count = "00";
    ap_sync_reg_busqueda_cam_U0_ap_ready = SC_LOGIC_0;
    busqueda_cam_U0_ap_ready_count = "00";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "top_function_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, tree1_V_address0, "(port)tree1_V_address0");
    sc_trace(mVcdFile, tree1_V_ce0, "(port)tree1_V_ce0");
    sc_trace(mVcdFile, tree1_V_d0, "(port)tree1_V_d0");
    sc_trace(mVcdFile, tree1_V_q0, "(port)tree1_V_q0");
    sc_trace(mVcdFile, tree1_V_we0, "(port)tree1_V_we0");
    sc_trace(mVcdFile, tree1_V_address1, "(port)tree1_V_address1");
    sc_trace(mVcdFile, tree1_V_ce1, "(port)tree1_V_ce1");
    sc_trace(mVcdFile, tree1_V_d1, "(port)tree1_V_d1");
    sc_trace(mVcdFile, tree1_V_q1, "(port)tree1_V_q1");
    sc_trace(mVcdFile, tree1_V_we1, "(port)tree1_V_we1");
    sc_trace(mVcdFile, tree2_V_address0, "(port)tree2_V_address0");
    sc_trace(mVcdFile, tree2_V_ce0, "(port)tree2_V_ce0");
    sc_trace(mVcdFile, tree2_V_d0, "(port)tree2_V_d0");
    sc_trace(mVcdFile, tree2_V_q0, "(port)tree2_V_q0");
    sc_trace(mVcdFile, tree2_V_we0, "(port)tree2_V_we0");
    sc_trace(mVcdFile, tree2_V_address1, "(port)tree2_V_address1");
    sc_trace(mVcdFile, tree2_V_ce1, "(port)tree2_V_ce1");
    sc_trace(mVcdFile, tree2_V_d1, "(port)tree2_V_d1");
    sc_trace(mVcdFile, tree2_V_q1, "(port)tree2_V_q1");
    sc_trace(mVcdFile, tree2_V_we1, "(port)tree2_V_we1");
    sc_trace(mVcdFile, nodo_V, "(port)nodo_V");
    sc_trace(mVcdFile, relationship_V, "(port)relationship_V");
    sc_trace(mVcdFile, fatherSearch, "(port)fatherSearch");
    sc_trace(mVcdFile, result_V_V_din, "(port)result_V_V_din");
    sc_trace(mVcdFile, result_V_V_full_n, "(port)result_V_V_full_n");
    sc_trace(mVcdFile, result_V_V_write, "(port)result_V_V_write");
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, top_function_entry3_U0_ap_start, "top_function_entry3_U0_ap_start");
    sc_trace(mVcdFile, top_function_entry3_U0_ap_done, "top_function_entry3_U0_ap_done");
    sc_trace(mVcdFile, top_function_entry3_U0_ap_continue, "top_function_entry3_U0_ap_continue");
    sc_trace(mVcdFile, top_function_entry3_U0_ap_idle, "top_function_entry3_U0_ap_idle");
    sc_trace(mVcdFile, top_function_entry3_U0_ap_ready, "top_function_entry3_U0_ap_ready");
    sc_trace(mVcdFile, top_function_entry3_U0_start_out, "top_function_entry3_U0_start_out");
    sc_trace(mVcdFile, top_function_entry3_U0_start_write, "top_function_entry3_U0_start_write");
    sc_trace(mVcdFile, top_function_entry3_U0_fatherSearch, "top_function_entry3_U0_fatherSearch");
    sc_trace(mVcdFile, top_function_entry3_U0_nodo_V_out_din, "top_function_entry3_U0_nodo_V_out_din");
    sc_trace(mVcdFile, top_function_entry3_U0_nodo_V_out_write, "top_function_entry3_U0_nodo_V_out_write");
    sc_trace(mVcdFile, top_function_entry3_U0_relationship_V_out_din, "top_function_entry3_U0_relationship_V_out_din");
    sc_trace(mVcdFile, top_function_entry3_U0_relationship_V_out_write, "top_function_entry3_U0_relationship_V_out_write");
    sc_trace(mVcdFile, top_function_entry3_U0_fatherSearch_out_din, "top_function_entry3_U0_fatherSearch_out_din");
    sc_trace(mVcdFile, top_function_entry3_U0_fatherSearch_out_write, "top_function_entry3_U0_fatherSearch_out_write");
    sc_trace(mVcdFile, top_function_entry43_U0_ap_start, "top_function_entry43_U0_ap_start");
    sc_trace(mVcdFile, top_function_entry43_U0_ap_done, "top_function_entry43_U0_ap_done");
    sc_trace(mVcdFile, top_function_entry43_U0_ap_continue, "top_function_entry43_U0_ap_continue");
    sc_trace(mVcdFile, top_function_entry43_U0_ap_idle, "top_function_entry43_U0_ap_idle");
    sc_trace(mVcdFile, top_function_entry43_U0_ap_ready, "top_function_entry43_U0_ap_ready");
    sc_trace(mVcdFile, top_function_entry43_U0_nodo_V_read, "top_function_entry43_U0_nodo_V_read");
    sc_trace(mVcdFile, top_function_entry43_U0_relationship_V_read, "top_function_entry43_U0_relationship_V_read");
    sc_trace(mVcdFile, top_function_entry43_U0_fatherSearch_read, "top_function_entry43_U0_fatherSearch_read");
    sc_trace(mVcdFile, top_function_entry43_U0_nodo_V_out_din, "top_function_entry43_U0_nodo_V_out_din");
    sc_trace(mVcdFile, top_function_entry43_U0_nodo_V_out_write, "top_function_entry43_U0_nodo_V_out_write");
    sc_trace(mVcdFile, top_function_entry43_U0_nodo_V_out1_din, "top_function_entry43_U0_nodo_V_out1_din");
    sc_trace(mVcdFile, top_function_entry43_U0_nodo_V_out1_write, "top_function_entry43_U0_nodo_V_out1_write");
    sc_trace(mVcdFile, top_function_entry43_U0_relationship_V_out_din, "top_function_entry43_U0_relationship_V_out_din");
    sc_trace(mVcdFile, top_function_entry43_U0_relationship_V_out_write, "top_function_entry43_U0_relationship_V_out_write");
    sc_trace(mVcdFile, top_function_entry43_U0_relationship_V_out2_din, "top_function_entry43_U0_relationship_V_out2_din");
    sc_trace(mVcdFile, top_function_entry43_U0_relationship_V_out2_write, "top_function_entry43_U0_relationship_V_out2_write");
    sc_trace(mVcdFile, top_function_entry43_U0_fatherSearch_out_din, "top_function_entry43_U0_fatherSearch_out_din");
    sc_trace(mVcdFile, top_function_entry43_U0_fatherSearch_out_write, "top_function_entry43_U0_fatherSearch_out_write");
    sc_trace(mVcdFile, top_function_entry43_U0_fatherSearch_out3_din, "top_function_entry43_U0_fatherSearch_out3_din");
    sc_trace(mVcdFile, top_function_entry43_U0_fatherSearch_out3_write, "top_function_entry43_U0_fatherSearch_out3_write");
    sc_trace(mVcdFile, busqueda_cam_1_U0_ap_start, "busqueda_cam_1_U0_ap_start");
    sc_trace(mVcdFile, busqueda_cam_1_U0_ap_done, "busqueda_cam_1_U0_ap_done");
    sc_trace(mVcdFile, busqueda_cam_1_U0_ap_continue, "busqueda_cam_1_U0_ap_continue");
    sc_trace(mVcdFile, busqueda_cam_1_U0_ap_idle, "busqueda_cam_1_U0_ap_idle");
    sc_trace(mVcdFile, busqueda_cam_1_U0_ap_ready, "busqueda_cam_1_U0_ap_ready");
    sc_trace(mVcdFile, busqueda_cam_1_U0_start_out, "busqueda_cam_1_U0_start_out");
    sc_trace(mVcdFile, busqueda_cam_1_U0_start_write, "busqueda_cam_1_U0_start_write");
    sc_trace(mVcdFile, busqueda_cam_1_U0_tree_V_address0, "busqueda_cam_1_U0_tree_V_address0");
    sc_trace(mVcdFile, busqueda_cam_1_U0_tree_V_ce0, "busqueda_cam_1_U0_tree_V_ce0");
    sc_trace(mVcdFile, busqueda_cam_1_U0_tree_V_address1, "busqueda_cam_1_U0_tree_V_address1");
    sc_trace(mVcdFile, busqueda_cam_1_U0_tree_V_ce1, "busqueda_cam_1_U0_tree_V_ce1");
    sc_trace(mVcdFile, busqueda_cam_1_U0_nodo_V_read, "busqueda_cam_1_U0_nodo_V_read");
    sc_trace(mVcdFile, busqueda_cam_1_U0_relationship_V_read, "busqueda_cam_1_U0_relationship_V_read");
    sc_trace(mVcdFile, busqueda_cam_1_U0_fatherSearch_read, "busqueda_cam_1_U0_fatherSearch_read");
    sc_trace(mVcdFile, busqueda_cam_1_U0_in1_V_V_din, "busqueda_cam_1_U0_in1_V_V_din");
    sc_trace(mVcdFile, busqueda_cam_1_U0_in1_V_V_write, "busqueda_cam_1_U0_in1_V_V_write");
    sc_trace(mVcdFile, busqueda_cam_1_U0_in1b_V_V_din, "busqueda_cam_1_U0_in1b_V_V_din");
    sc_trace(mVcdFile, busqueda_cam_1_U0_in1b_V_V_write, "busqueda_cam_1_U0_in1b_V_V_write");
    sc_trace(mVcdFile, busqueda_cam_U0_ap_start, "busqueda_cam_U0_ap_start");
    sc_trace(mVcdFile, busqueda_cam_U0_ap_done, "busqueda_cam_U0_ap_done");
    sc_trace(mVcdFile, busqueda_cam_U0_ap_continue, "busqueda_cam_U0_ap_continue");
    sc_trace(mVcdFile, busqueda_cam_U0_ap_idle, "busqueda_cam_U0_ap_idle");
    sc_trace(mVcdFile, busqueda_cam_U0_ap_ready, "busqueda_cam_U0_ap_ready");
    sc_trace(mVcdFile, busqueda_cam_U0_tree_V_address0, "busqueda_cam_U0_tree_V_address0");
    sc_trace(mVcdFile, busqueda_cam_U0_tree_V_ce0, "busqueda_cam_U0_tree_V_ce0");
    sc_trace(mVcdFile, busqueda_cam_U0_tree_V_address1, "busqueda_cam_U0_tree_V_address1");
    sc_trace(mVcdFile, busqueda_cam_U0_tree_V_ce1, "busqueda_cam_U0_tree_V_ce1");
    sc_trace(mVcdFile, busqueda_cam_U0_nodo_V_read, "busqueda_cam_U0_nodo_V_read");
    sc_trace(mVcdFile, busqueda_cam_U0_relationship_V_read, "busqueda_cam_U0_relationship_V_read");
    sc_trace(mVcdFile, busqueda_cam_U0_fatherSearch_read, "busqueda_cam_U0_fatherSearch_read");
    sc_trace(mVcdFile, busqueda_cam_U0_in2_V_V_din, "busqueda_cam_U0_in2_V_V_din");
    sc_trace(mVcdFile, busqueda_cam_U0_in2_V_V_write, "busqueda_cam_U0_in2_V_V_write");
    sc_trace(mVcdFile, busqueda_cam_U0_in2b_V_V_din, "busqueda_cam_U0_in2b_V_V_din");
    sc_trace(mVcdFile, busqueda_cam_U0_in2b_V_V_write, "busqueda_cam_U0_in2b_V_V_write");
    sc_trace(mVcdFile, combinar_U0_ap_start, "combinar_U0_ap_start");
    sc_trace(mVcdFile, combinar_U0_ap_done, "combinar_U0_ap_done");
    sc_trace(mVcdFile, combinar_U0_ap_continue, "combinar_U0_ap_continue");
    sc_trace(mVcdFile, combinar_U0_ap_idle, "combinar_U0_ap_idle");
    sc_trace(mVcdFile, combinar_U0_ap_ready, "combinar_U0_ap_ready");
    sc_trace(mVcdFile, combinar_U0_result_V_V_din, "combinar_U0_result_V_V_din");
    sc_trace(mVcdFile, combinar_U0_result_V_V_write, "combinar_U0_result_V_V_write");
    sc_trace(mVcdFile, combinar_U0_in1_V_V_read, "combinar_U0_in1_V_V_read");
    sc_trace(mVcdFile, combinar_U0_in2_V_V_read, "combinar_U0_in2_V_V_read");
    sc_trace(mVcdFile, combinar_U0_in1b_V_V_read, "combinar_U0_in1b_V_V_read");
    sc_trace(mVcdFile, combinar_U0_in2b_V_V_read, "combinar_U0_in2b_V_V_read");
    sc_trace(mVcdFile, ap_sync_continue, "ap_sync_continue");
    sc_trace(mVcdFile, nodo_V_c1_full_n, "nodo_V_c1_full_n");
    sc_trace(mVcdFile, nodo_V_c1_dout, "nodo_V_c1_dout");
    sc_trace(mVcdFile, nodo_V_c1_empty_n, "nodo_V_c1_empty_n");
    sc_trace(mVcdFile, relationship_V_c2_full_n, "relationship_V_c2_full_n");
    sc_trace(mVcdFile, relationship_V_c2_dout, "relationship_V_c2_dout");
    sc_trace(mVcdFile, relationship_V_c2_empty_n, "relationship_V_c2_empty_n");
    sc_trace(mVcdFile, fatherSearch_c3_full_n, "fatherSearch_c3_full_n");
    sc_trace(mVcdFile, fatherSearch_c3_dout, "fatherSearch_c3_dout");
    sc_trace(mVcdFile, fatherSearch_c3_empty_n, "fatherSearch_c3_empty_n");
    sc_trace(mVcdFile, nodo_V_c_full_n, "nodo_V_c_full_n");
    sc_trace(mVcdFile, nodo_V_c_dout, "nodo_V_c_dout");
    sc_trace(mVcdFile, nodo_V_c_empty_n, "nodo_V_c_empty_n");
    sc_trace(mVcdFile, nodo_V_c7_full_n, "nodo_V_c7_full_n");
    sc_trace(mVcdFile, nodo_V_c7_dout, "nodo_V_c7_dout");
    sc_trace(mVcdFile, nodo_V_c7_empty_n, "nodo_V_c7_empty_n");
    sc_trace(mVcdFile, relationship_V_c_full_n, "relationship_V_c_full_n");
    sc_trace(mVcdFile, relationship_V_c_dout, "relationship_V_c_dout");
    sc_trace(mVcdFile, relationship_V_c_empty_n, "relationship_V_c_empty_n");
    sc_trace(mVcdFile, relationship_V_c8_full_n, "relationship_V_c8_full_n");
    sc_trace(mVcdFile, relationship_V_c8_dout, "relationship_V_c8_dout");
    sc_trace(mVcdFile, relationship_V_c8_empty_n, "relationship_V_c8_empty_n");
    sc_trace(mVcdFile, fatherSearch_c_full_n, "fatherSearch_c_full_n");
    sc_trace(mVcdFile, fatherSearch_c_dout, "fatherSearch_c_dout");
    sc_trace(mVcdFile, fatherSearch_c_empty_n, "fatherSearch_c_empty_n");
    sc_trace(mVcdFile, fatherSearch_c9_full_n, "fatherSearch_c9_full_n");
    sc_trace(mVcdFile, fatherSearch_c9_dout, "fatherSearch_c9_dout");
    sc_trace(mVcdFile, fatherSearch_c9_empty_n, "fatherSearch_c9_empty_n");
    sc_trace(mVcdFile, in1_V_V_full_n, "in1_V_V_full_n");
    sc_trace(mVcdFile, in1_V_V_dout, "in1_V_V_dout");
    sc_trace(mVcdFile, in1_V_V_empty_n, "in1_V_V_empty_n");
    sc_trace(mVcdFile, in1b_V_V_full_n, "in1b_V_V_full_n");
    sc_trace(mVcdFile, in1b_V_V_dout, "in1b_V_V_dout");
    sc_trace(mVcdFile, in1b_V_V_empty_n, "in1b_V_V_empty_n");
    sc_trace(mVcdFile, in2_V_V_full_n, "in2_V_V_full_n");
    sc_trace(mVcdFile, in2_V_V_dout, "in2_V_V_dout");
    sc_trace(mVcdFile, in2_V_V_empty_n, "in2_V_V_empty_n");
    sc_trace(mVcdFile, in2b_V_V_full_n, "in2b_V_V_full_n");
    sc_trace(mVcdFile, in2b_V_V_dout, "in2b_V_V_dout");
    sc_trace(mVcdFile, in2b_V_V_empty_n, "in2b_V_V_empty_n");
    sc_trace(mVcdFile, ap_sync_done, "ap_sync_done");
    sc_trace(mVcdFile, ap_sync_ready, "ap_sync_ready");
    sc_trace(mVcdFile, ap_sync_reg_top_function_entry3_U0_ap_ready, "ap_sync_reg_top_function_entry3_U0_ap_ready");
    sc_trace(mVcdFile, ap_sync_top_function_entry3_U0_ap_ready, "ap_sync_top_function_entry3_U0_ap_ready");
    sc_trace(mVcdFile, top_function_entry3_U0_ap_ready_count, "top_function_entry3_U0_ap_ready_count");
    sc_trace(mVcdFile, ap_sync_reg_busqueda_cam_1_U0_ap_ready, "ap_sync_reg_busqueda_cam_1_U0_ap_ready");
    sc_trace(mVcdFile, ap_sync_busqueda_cam_1_U0_ap_ready, "ap_sync_busqueda_cam_1_U0_ap_ready");
    sc_trace(mVcdFile, busqueda_cam_1_U0_ap_ready_count, "busqueda_cam_1_U0_ap_ready_count");
    sc_trace(mVcdFile, ap_sync_reg_busqueda_cam_U0_ap_ready, "ap_sync_reg_busqueda_cam_U0_ap_ready");
    sc_trace(mVcdFile, ap_sync_busqueda_cam_U0_ap_ready, "ap_sync_busqueda_cam_U0_ap_ready");
    sc_trace(mVcdFile, busqueda_cam_U0_ap_ready_count, "busqueda_cam_U0_ap_ready_count");
    sc_trace(mVcdFile, start_for_top_function_entry43_U0_din, "start_for_top_function_entry43_U0_din");
    sc_trace(mVcdFile, start_for_top_function_entry43_U0_full_n, "start_for_top_function_entry43_U0_full_n");
    sc_trace(mVcdFile, start_for_top_function_entry43_U0_dout, "start_for_top_function_entry43_U0_dout");
    sc_trace(mVcdFile, start_for_top_function_entry43_U0_empty_n, "start_for_top_function_entry43_U0_empty_n");
    sc_trace(mVcdFile, top_function_entry43_U0_start_full_n, "top_function_entry43_U0_start_full_n");
    sc_trace(mVcdFile, top_function_entry43_U0_start_write, "top_function_entry43_U0_start_write");
    sc_trace(mVcdFile, start_for_combinar_U0_din, "start_for_combinar_U0_din");
    sc_trace(mVcdFile, start_for_combinar_U0_full_n, "start_for_combinar_U0_full_n");
    sc_trace(mVcdFile, start_for_combinar_U0_dout, "start_for_combinar_U0_dout");
    sc_trace(mVcdFile, start_for_combinar_U0_empty_n, "start_for_combinar_U0_empty_n");
    sc_trace(mVcdFile, busqueda_cam_U0_start_full_n, "busqueda_cam_U0_start_full_n");
    sc_trace(mVcdFile, busqueda_cam_U0_start_write, "busqueda_cam_U0_start_write");
    sc_trace(mVcdFile, combinar_U0_start_full_n, "combinar_U0_start_full_n");
    sc_trace(mVcdFile, combinar_U0_start_write, "combinar_U0_start_write");
#endif

    }
    mHdltvinHandle.open("top_function.hdltvin.dat");
    mHdltvoutHandle.open("top_function.hdltvout.dat");
}

top_function::~top_function() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete top_function_entry3_U0;
    delete top_function_entry43_U0;
    delete busqueda_cam_1_U0;
    delete busqueda_cam_U0;
    delete combinar_U0;
    delete nodo_V_c1_U;
    delete relationship_V_c2_U;
    delete fatherSearch_c3_U;
    delete nodo_V_c_U;
    delete nodo_V_c7_U;
    delete relationship_V_c_U;
    delete relationship_V_c8_U;
    delete fatherSearch_c_U;
    delete fatherSearch_c9_U;
    delete in1_V_V_U;
    delete in1b_V_V_U;
    delete in2_V_V_U;
    delete in2b_V_V_U;
    delete start_for_top_funbkb_U;
    delete start_for_combinacud_U;
}

void top_function::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void top_function::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_sync_reg_busqueda_cam_1_U0_ap_ready = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (ap_start.read() & 
             ap_sync_ready.read()))) {
            ap_sync_reg_busqueda_cam_1_U0_ap_ready = ap_const_logic_0;
        } else {
            ap_sync_reg_busqueda_cam_1_U0_ap_ready = ap_sync_busqueda_cam_1_U0_ap_ready.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_sync_reg_busqueda_cam_U0_ap_ready = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (ap_start.read() & 
             ap_sync_ready.read()))) {
            ap_sync_reg_busqueda_cam_U0_ap_ready = ap_const_logic_0;
        } else {
            ap_sync_reg_busqueda_cam_U0_ap_ready = ap_sync_busqueda_cam_U0_ap_ready.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_sync_reg_top_function_entry3_U0_ap_ready = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (ap_start.read() & 
             ap_sync_ready.read()))) {
            ap_sync_reg_top_function_entry3_U0_ap_ready = ap_const_logic_0;
        } else {
            ap_sync_reg_top_function_entry3_U0_ap_ready = ap_sync_top_function_entry3_U0_ap_ready.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sync_ready.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, busqueda_cam_1_U0_ap_ready.read()))) {
        busqueda_cam_1_U0_ap_ready_count = (!busqueda_cam_1_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(busqueda_cam_1_U0_ap_ready_count.read()) - sc_biguint<2>(ap_const_lv2_1));
    } else if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_sync_ready.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, busqueda_cam_1_U0_ap_ready.read()))) {
        busqueda_cam_1_U0_ap_ready_count = (!busqueda_cam_1_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(busqueda_cam_1_U0_ap_ready_count.read()) + sc_biguint<2>(ap_const_lv2_1));
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sync_ready.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, busqueda_cam_U0_ap_ready.read()))) {
        busqueda_cam_U0_ap_ready_count = (!busqueda_cam_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(busqueda_cam_U0_ap_ready_count.read()) - sc_biguint<2>(ap_const_lv2_1));
    } else if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_sync_ready.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, busqueda_cam_U0_ap_ready.read()))) {
        busqueda_cam_U0_ap_ready_count = (!busqueda_cam_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(busqueda_cam_U0_ap_ready_count.read()) + sc_biguint<2>(ap_const_lv2_1));
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_0, top_function_entry3_U0_ap_ready.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sync_ready.read()))) {
        top_function_entry3_U0_ap_ready_count = (!top_function_entry3_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(top_function_entry3_U0_ap_ready_count.read()) - sc_biguint<2>(ap_const_lv2_1));
    } else if ((esl_seteq<1,1,1>(top_function_entry3_U0_ap_ready.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_logic_0, ap_sync_ready.read()))) {
        top_function_entry3_U0_ap_ready_count = (!top_function_entry3_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(top_function_entry3_U0_ap_ready_count.read()) + sc_biguint<2>(ap_const_lv2_1));
    }
}

void top_function::thread_ap_done() {
    ap_done = combinar_U0_ap_done.read();
}

void top_function::thread_ap_idle() {
    ap_idle = (top_function_entry3_U0_ap_idle.read() & top_function_entry43_U0_ap_idle.read() & busqueda_cam_1_U0_ap_idle.read() & busqueda_cam_U0_ap_idle.read() & combinar_U0_ap_idle.read());
}

void top_function::thread_ap_ready() {
    ap_ready = ap_sync_ready.read();
}

void top_function::thread_ap_sync_busqueda_cam_1_U0_ap_ready() {
    ap_sync_busqueda_cam_1_U0_ap_ready = (busqueda_cam_1_U0_ap_ready.read() | ap_sync_reg_busqueda_cam_1_U0_ap_ready.read());
}

void top_function::thread_ap_sync_busqueda_cam_U0_ap_ready() {
    ap_sync_busqueda_cam_U0_ap_ready = (busqueda_cam_U0_ap_ready.read() | ap_sync_reg_busqueda_cam_U0_ap_ready.read());
}

void top_function::thread_ap_sync_continue() {
    ap_sync_continue = ap_const_logic_1;
}

void top_function::thread_ap_sync_done() {
    ap_sync_done = combinar_U0_ap_done.read();
}

void top_function::thread_ap_sync_ready() {
    ap_sync_ready = (ap_sync_top_function_entry3_U0_ap_ready.read() & ap_sync_busqueda_cam_1_U0_ap_ready.read() & ap_sync_busqueda_cam_U0_ap_ready.read());
}

void top_function::thread_ap_sync_top_function_entry3_U0_ap_ready() {
    ap_sync_top_function_entry3_U0_ap_ready = (top_function_entry3_U0_ap_ready.read() | ap_sync_reg_top_function_entry3_U0_ap_ready.read());
}

void top_function::thread_busqueda_cam_1_U0_ap_continue() {
    busqueda_cam_1_U0_ap_continue = ap_const_logic_1;
}

void top_function::thread_busqueda_cam_1_U0_ap_start() {
    busqueda_cam_1_U0_ap_start = (ap_start.read() & (ap_sync_reg_busqueda_cam_1_U0_ap_ready.read() ^ 
  ap_const_logic_1));
}

void top_function::thread_busqueda_cam_U0_ap_continue() {
    busqueda_cam_U0_ap_continue = ap_const_logic_1;
}

void top_function::thread_busqueda_cam_U0_ap_start() {
    busqueda_cam_U0_ap_start = (ap_start.read() & (ap_sync_reg_busqueda_cam_U0_ap_ready.read() ^ 
  ap_const_logic_1));
}

void top_function::thread_busqueda_cam_U0_start_full_n() {
    busqueda_cam_U0_start_full_n = ap_const_logic_1;
}

void top_function::thread_busqueda_cam_U0_start_write() {
    busqueda_cam_U0_start_write = ap_const_logic_0;
}

void top_function::thread_combinar_U0_ap_continue() {
    combinar_U0_ap_continue = ap_const_logic_1;
}

void top_function::thread_combinar_U0_ap_start() {
    combinar_U0_ap_start = start_for_combinar_U0_empty_n.read();
}

void top_function::thread_combinar_U0_start_full_n() {
    combinar_U0_start_full_n = ap_const_logic_1;
}

void top_function::thread_combinar_U0_start_write() {
    combinar_U0_start_write = ap_const_logic_0;
}

void top_function::thread_result_V_V_din() {
    result_V_V_din = combinar_U0_result_V_V_din.read();
}

void top_function::thread_result_V_V_write() {
    result_V_V_write = combinar_U0_result_V_V_write.read();
}

void top_function::thread_start_for_combinar_U0_din() {
    start_for_combinar_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void top_function::thread_start_for_top_function_entry43_U0_din() {
    start_for_top_function_entry43_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void top_function::thread_top_function_entry3_U0_ap_continue() {
    top_function_entry3_U0_ap_continue = ap_const_logic_1;
}

void top_function::thread_top_function_entry3_U0_ap_start() {
    top_function_entry3_U0_ap_start = (ap_start.read() & (ap_sync_reg_top_function_entry3_U0_ap_ready.read() ^ 
  ap_const_logic_1));
}

void top_function::thread_top_function_entry3_U0_fatherSearch() {
    top_function_entry3_U0_fatherSearch =  (sc_lv<1>) (fatherSearch.read());
}

void top_function::thread_top_function_entry43_U0_ap_continue() {
    top_function_entry43_U0_ap_continue = ap_const_logic_1;
}

void top_function::thread_top_function_entry43_U0_ap_start() {
    top_function_entry43_U0_ap_start = start_for_top_function_entry43_U0_empty_n.read();
}

void top_function::thread_top_function_entry43_U0_start_full_n() {
    top_function_entry43_U0_start_full_n = ap_const_logic_1;
}

void top_function::thread_top_function_entry43_U0_start_write() {
    top_function_entry43_U0_start_write = ap_const_logic_0;
}

void top_function::thread_tree1_V_address0() {
    tree1_V_address0 = busqueda_cam_1_U0_tree_V_address0.read();
}

void top_function::thread_tree1_V_address1() {
    tree1_V_address1 = busqueda_cam_1_U0_tree_V_address1.read();
}

void top_function::thread_tree1_V_ce0() {
    tree1_V_ce0 = busqueda_cam_1_U0_tree_V_ce0.read();
}

void top_function::thread_tree1_V_ce1() {
    tree1_V_ce1 = busqueda_cam_1_U0_tree_V_ce1.read();
}

void top_function::thread_tree1_V_d0() {
    tree1_V_d0 = ap_const_lv24_0;
}

void top_function::thread_tree1_V_d1() {
    tree1_V_d1 = ap_const_lv24_0;
}

void top_function::thread_tree1_V_we0() {
    tree1_V_we0 = ap_const_logic_0;
}

void top_function::thread_tree1_V_we1() {
    tree1_V_we1 = ap_const_logic_0;
}

void top_function::thread_tree2_V_address0() {
    tree2_V_address0 = busqueda_cam_U0_tree_V_address0.read();
}

void top_function::thread_tree2_V_address1() {
    tree2_V_address1 = busqueda_cam_U0_tree_V_address1.read();
}

void top_function::thread_tree2_V_ce0() {
    tree2_V_ce0 = busqueda_cam_U0_tree_V_ce0.read();
}

void top_function::thread_tree2_V_ce1() {
    tree2_V_ce1 = busqueda_cam_U0_tree_V_ce1.read();
}

void top_function::thread_tree2_V_d0() {
    tree2_V_d0 = ap_const_lv24_0;
}

void top_function::thread_tree2_V_d1() {
    tree2_V_d1 = ap_const_lv24_0;
}

void top_function::thread_tree2_V_we0() {
    tree2_V_we0 = ap_const_logic_0;
}

void top_function::thread_tree2_V_we1() {
    tree2_V_we1 = ap_const_logic_0;
}

void top_function::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvoutHandle << mComma << "{"  <<  " \"tree1_V_address0\" :  \"" << tree1_V_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"tree1_V_ce0\" :  \"" << tree1_V_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"tree1_V_d0\" :  \"" << tree1_V_d0.read() << "\" ";
        mHdltvinHandle << mComma << "{"  <<  " \"tree1_V_q0\" :  \"" << tree1_V_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"tree1_V_we0\" :  \"" << tree1_V_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"tree1_V_address1\" :  \"" << tree1_V_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"tree1_V_ce1\" :  \"" << tree1_V_ce1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"tree1_V_d1\" :  \"" << tree1_V_d1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"tree1_V_q1\" :  \"" << tree1_V_q1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"tree1_V_we1\" :  \"" << tree1_V_we1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"tree2_V_address0\" :  \"" << tree2_V_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"tree2_V_ce0\" :  \"" << tree2_V_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"tree2_V_d0\" :  \"" << tree2_V_d0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"tree2_V_q0\" :  \"" << tree2_V_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"tree2_V_we0\" :  \"" << tree2_V_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"tree2_V_address1\" :  \"" << tree2_V_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"tree2_V_ce1\" :  \"" << tree2_V_ce1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"tree2_V_d1\" :  \"" << tree2_V_d1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"tree2_V_q1\" :  \"" << tree2_V_q1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"tree2_V_we1\" :  \"" << tree2_V_we1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"nodo_V\" :  \"" << nodo_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"relationship_V\" :  \"" << relationship_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"fatherSearch\" :  \"" << fatherSearch.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"result_V_V_din\" :  \"" << result_V_V_din.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"result_V_V_full_n\" :  \"" << result_V_V_full_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"result_V_V_write\" :  \"" << result_V_V_write.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

