#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("tree_V_address0", 10, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("tree_V_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("tree_V_d0", 24, hls_out, 0, "ap_memory", "mem_din", 1),
	Port_Property("tree_V_q0", 24, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("tree_V_we0", 1, hls_out, 0, "ap_memory", "mem_we", 1),
	Port_Property("tree_V_address1", 10, hls_out, 0, "ap_memory", "MemPortADDR2", 1),
	Port_Property("tree_V_ce1", 1, hls_out, 0, "ap_memory", "MemPortCE2", 1),
	Port_Property("tree_V_d1", 24, hls_out, 0, "ap_memory", "mem_din", 1),
	Port_Property("tree_V_q1", 24, hls_in, 0, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("tree_V_we1", 1, hls_out, 0, "ap_memory", "mem_we", 1),
	Port_Property("nodo_V", 11, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("relationship_V", 2, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("fatherSearch", 1, hls_in, 3, "ap_none", "in_data", 1),
	Port_Property("result_V_V_din", 11, hls_out, 4, "ap_fifo", "fifo_data", 1),
	Port_Property("result_V_V_full_n", 1, hls_in, 4, "ap_fifo", "fifo_status", 1),
	Port_Property("result_V_V_write", 1, hls_out, 4, "ap_fifo", "fifo_update", 1),
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "top_function";
